### ISSUE TITLE
Javadoc links may link to old Javadoc versions

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#1009]
Renaming `io.zeebe.*` to `io.camunda.*` we seemed to rename the text but not the actual link, causing the links to send users to old versions of the Javadocs.

https://docs.camunda.io/docs/apis-clients/java-client/#bootstrapping

`See [io.camunda.zeebe.client.ZeebeClientBuilder](https://javadoc.io/doc/io.zeebe/zeebe-client-java/latest/io/zeebe/client/ZeebeClientBuilder.html) for a description of all available configuration properties.`

should be changed to 

`See [io.camunda.zeebe.client.ZeebeClientBuilder](https://javadoc.io/doc/io.camunda/zeebe-client-java/latest/io/camunda/zeebe/client/ZeebeClientBuilder.html) for a description of all available configuration properties.`

This is only one example. To close out this issue with a PR, please search the docs for other instances of links to `io.zeebe.*`.

Special thanks to @falko for spotting this.

**Comment by akeller** [comment]
@christinaausley this is super subtle but essentially in the URLs you are looking to replace `io.zeebe` with `io.camunda` **and** `/io/zeebe/` with `/io/camunda/`. These should be isolated to the Java client pages and this may be the only one, I didn't look. Are you up for chasing this one down?

**Comment by christinaausley** [comment]
Happy to tackle this!
