### ISSUE TITLE
Hint people to not connect ingress unproected to the Internet

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-platform-docs#1021]
We are regularly seeing that users add Ingress for the Zeebe Gateway and open this up unprotected to the Internet, because they think they need that access (e.g. to deploy models). 

@falko proposed some BP like:

> for development, you can use a kubectl port forwarding to connect Modeler or zbctl. For production, we recommend that you let your client application, which runs inside the same k8s cluster, deploy the models upon startup. Spring Zeebe even provides a convenient annotation for that. Less common but also possible is to package the models as a k8s configmap and deploy them with zbctl running as a job using the Zeebe image.

We might need to figure out our best practice and how to document it.

**Comment by akeller** [comment]
@berndruecker is this still a problem? Is this something you will work on?

**Comment by megglos** [comment]
With https://github.com/camunda/camunda-platform-helm/issues/608 the zeebe gateway is secured by default going forward, would that change the situation?

**Comment by akeller** [comment]
I'll check in with @berndruecker and see if we can close this out.
