### ISSUE TITLE
Bring docusaurus dependencies up to date

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-platform-docs#1024]
Docusaurus dependencies have been stuck at version beta-15 for some time, due to Algolia DocSearch migration. For security & maintenance reasons, we should bring them as up to date as possible. 

Work included in this issue (some may be combined if they prove to be small/easy updates): 

- [x] #1015 
- [x] #1036 
- [x] #1068 
- [x] #1085
- [x] #1100
- [x] #1025 
- [x] #1114 

cc @akeller for visibility

**Comment by akeller** [comment]
Cheering you on from the sidelines! Let me know if you need extra eyes on anything.

**Comment by pepopowitz** [comment]
Marking this done!!!! We're not fully up-to-date because they just released 2.0.0, but this got us close enough that future updates should be pretty routine.
