### ISSUE TITLE
Documentation Bug: As a reader of documentation I'm expecting to see proper configuration options for the management port of Zeebe Gateway and Zeebe Broker

### ISSUE THREAD

**Issue by aivinog1** [camunda/camunda-platform-docs#1028]
The problem with [this page](https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/health/), it reflects removed configuration settings about management ports. Also, see: #861

**Comment by akeller** [comment]
@aivinog1 is this still a problem? I'm having trouble following the linked issue. Are you expecting to see an additional health status check?

**Comment by aivinog1** [comment]
Hello, @akeller! 
The problem is, as I remember, in the `zeebe.broker.network.monitoringApi.port` property's usage. Since Zeebe Broker relies on the `SERVER_PORT` and `SERVER_HOST` property, and the `zeebe.broker.network.monitoringApi.port` is not used anymore.
Source: https://github.com/camunda/camunda-platform-docs/blob/cc3e89d45bd5f2b9a5e40b445df83ab3d03bd610/docs/guides/update-guide/120-to-130.md?plain=1#L21-L53

**Comment by megglos** [comment]
@rodrigo-lourenco-lopes just assigned you this as a first doc issue to get familiar with the docs

**Comment by rodrigo-lourenco-lopes** [comment]
Hi @aivinog1!

Since we are no longer able to access these health check endpoints for the brokers, to update this document would be simple to remove this documentation, correct? From what I understood from that .yaml file this functionality was removed.
Or is there any other available endpoint for these checks?

**Comment by megglos** [comment]
Reopening as there was a misunderstanding on this, the endpoints are still available on the broker and actually used for health checks indeed.
