### ISSUE TITLE
Add instructions for how to run Prettier to docs guidance

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#1033]
> OK - I take back might "small change" ;-) Sorry for the noise, and thanks! **How do I run prettier locally to fix those problems?**

_Originally posted by @berndruecker in https://github.com/camunda/camunda-platform-docs/issues/1026#issuecomment-1175826452_

**Comment by akeller** [comment]
Documented here - https://github.com/camunda/camunda-platform-docs/blob/19a32339065d85593f6cd12a95313b6aea530183/CONTRIBUTING.MD#code-formatting

**Comment by akeller** [comment]
I actually think the problem requires us to reevaluate the `/howtos/` and revamp the README now that the project has grown.

**Comment by akeller** [comment]
@pepopowitz the biggest issue I see with Prettier is changes made in the browser (GitHub UI). That makes me think we can close this and focus on #1104. WDYT?

**Comment by pepopowitz** [comment]
@akeller yes, I'm 100% in agreement.
