### ISSUE TITLE
Create entry point for "Integration Framework" documentation in the Modeler component sections

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-platform-docs#1050]
With the introduction of the [connector template editor in the Web Modeler](https://github.com/camunda/product-hub/issues/64), element templates are no longer a Desktop Modeler - only feature. Therefore, we need to document it in the scope of the Web Modeler, too.

Once we retrieve the [latest element template schema](https://github.com/bpmn-io/bpmn-js-properties-panel/issues/690) in the Web Modeler that adds support for conditional templates, we need to move the [element template docs](https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/defining-templates/) out of the Desktop Modeler sections into a generic one and reference it from the Web Modeler sections (https://docs.camunda.io/docs/components/modeler/web-modeler/connectors/) (there is already a reference into the Desktop documentation that needs to be updated). 

This can be challenging due to the "Element Template"/"Connector Template" name clash, so I prefer naming the new common section "Integration Framework" and place it into the docs like this (note it is just a mockup)

![image](https://user-images.githubusercontent.com/56470362/178225547-254e94ae-278b-486f-a02e-d832ba8f1f4d.png)

and have the 2 dedicated sections for both Web and Desktop documentation refer to it, but with additional, product-specific details (i.e. how to include them in Desktop vs. how to write them in Web).

And we should also remove this [notice](https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/about-templates/), because it is now part of the product we sell and thus public+reliable:

![image](https://user-images.githubusercontent.com/56470362/178225663-7edf7829-b323-4d20-aaab-3c141eb1e45a.png)

**Comment by MaxTru** [comment]
Will be driven by Connectors Team

**Comment by akeller** [comment]
This aligns with the docs vision nicely. Thank you 😄

**Comment by MaxTru** [comment]
> This aligns with the docs vision nicely. Thank you smile

Thanks @akeller for confirming.

With this issue we would like to restructure the Connector Docs. Do we already have a concept in place for Connectors that we could re-use or build on?

**Comment by MaxTru** [comment]
> We don't have a concept in place beyond what was mentioned above, moving the content outside the scope of just Desktop Modeler and then documenting specific for Desktop and Web modeler within their component sections (if applicable). I'm happy to meet to discuss more specifics, but I'm not entirely sure what additional documentation is coming for connectors.

Thanks Amara.

We (Connectors Team) will sketch something and come back to you.

**Comment by MaxTru** [comment]
Current thinking:

![image](https://user-images.githubusercontent.com/42800119/178504115-e2bfd701-10ed-4e94-8c6b-561ab0920c39.png)

**Comment by christian-konrad** [comment]
@MaxTru great approach.

**Comment by MaxTru** [comment]
Will tackle this after my vacation (in ~3 weeks)

**Comment by MaxTru** [comment]
Hi @akeller,

this is to inform you that we will pull this into the current iteration. So please expect at PR for this in the next 2 weeks. Hope this is okay.

Thanks
Max

**Comment by akeller** [comment]
I left a comment on the draft PR since we are planning to merge the versioning work this week, which may require some significant changes to the PR (or you may opt to reopen the PR). Steve will follow up on the PR with recommendations or guidance.

**Comment by MaxTru** [comment]
> I left a comment on the draft PR since we are planning to merge the versioning work this week, which may require some significant changes to the PR (or you may opt to reopen the PR). Steve will follow up on the PR with recommendations or guidance.

I read it and moved the changes to `8.0` and `next`. So this should be solved.
