### ISSUE TITLE
Documentation about identity providers for SaaS

### ISSUE THREAD

**Issue by aleksander-dytko** [camunda/camunda-platform-docs#1051]
### Customer problem

- As a customer, I'm not able to find if Camunda 8 SaaS offers identity providers integration and how to do that - there is no documentation about that. 

### User story
- As a customer I'm able to find documentation about supported IAM providers such as Keycloak, LDAP, AD
- As a developer I know what Camunda needs from my organization side to be able to connect IAM with Camunda 8

**Comment by akeller** [comment]
@aleksander-dytko is this still an open item? You mention Identity providers for SaaS, do you mean external identity providers as documented here? - https://docs.camunda.io/docs/components/console/manage-organization/external-sso/

**Comment by aleksander-dytko** [comment]
Yes - I mean exactly that. Thanks for following up on this issue!
