### ISSUE TITLE
Secrets document is not precise

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-platform-docs#1063]
### Describe the bug

https://docs.camunda.io/docs/components/console/manage-clusters/manage-secrets/ explains that:
> Now you can reference your Secret like this: secrets.MY_API_KEY in any connector field in the properties panel that is marked with the FEEL Expression icon: feel-icon. Keep in mind Secrets are not variables and must be wrapped in double quotes as follows:

This is not correct. Secrets can be used in some fields in the propPanel. They are inserted not as variable, but using string replace. Hence in some places they have to be put into `"`.

### Steps to reproduce

Read https://docs.camunda.io/docs/components/console/manage-clusters/manage-secrets/ 

### Expected behavior

* Clarify that secrets are not variables, but are replaced (as in string replace)
* Clarify that secrets can be put into some fields.
* Clarify which fields allow secrets (connector-by-connector)
  * Alternative: for these fields, add directly to the field description in the propPanel that one may refrence secrets

### Environment

n/a

**Comment by wollefitz** [comment]
Additionally to what is written in the description, as a user I would expect the documentation mention limitations like https://github.com/camunda/cloud-connector-http-json/issues/45 (i.e. at least for the REST Connector, secrets are only replaced if the string only consists of the secret and nothing else) until this behavior is changed. This should be covered by "Clarify which fields allow secrets (connector-by-connector)".

**Comment by igpetrov** [comment]
@akulminskyi - FYI assigned this task to you.

**Comment by MaxTru** [comment]
Corrected. Thanks for highlight. Will close.

**Comment by tmetzke** [comment]
Glad this improves it 👍
