### ISSUE TITLE
Standardize Consistent Screenshots

### ISSUE THREAD

**Issue by urbanisierung** [camunda/camunda-platform-docs#110]
Several documentation pages describing customer facing apps (cloud console, operate, tasklist, zeebe modeler) use screenshots to guide the user. All screenshots look differently.

Discuss and define Guidelines for Screenshots

Long-term: automate screenshot generation

/cc akeller pihme ralfpuchert

**Comment by akeller** [comment]
Follow up here - @christinaausley @pepopowitz are looking into the foundational work for **Discuss and define Guidelines for Screenshots**. They are meeting with component teams after screenshots have been moved from C7 docs or created new for C8. 

I feel like we are at a good point now to work towards providing guidelines for screenshot consistency and then talk about automating screenshot generation (from a unified perspective). 

This issue and #115 will remain open to represent the work happening with this topic.

**Comment by akeller** [comment]
A newer item that came up recently was content in the screenshots - the personal identifier info is not consistent either - Jane Doe vs. Max Mustermann. We'll need to also consider this as we work towards guidelines.

But first, let's see how teams are handling screenshots today so we understand what it's going to take to make them consistent!

**Comment by christinaausley** [comment]
Note that I'm currently working with each component team to document the current methodology for screenshot automation across teams. Once these process differences/similarities are established and documented this quarter, I'm looking forward to standardizing on a clean, dependable, organized screenshot automation process.

Will share a link to the documented processes towards the end of this quarter for further discussion.

**Comment by akeller** [comment]
@christinaausley can I assign this to you to continue leading?

**Comment by akeller** [comment]
Standardization discussion for borders is happening over here - https://github.com/camunda/developer-experience/issues/24

**Comment by akeller** [comment]
Outside of the border discussion, is there anything else going on or remaining with this issue @christinaausley?

**Comment by christinaausley** [comment]
After talking with @MaxTru, he recommended I pause this work until the Tasklist/Operate teams have a larger capacity to assist.

That being said, we have achieved several milestones in the process of standardizing screenshots:
- Documented existing screenshot automation processes both internally and externally, which will be helpful in moving forward once this work is ready to be picked up again between myself and the engineering teams.
- Standardized Zeebe diagrams and documented methodology for creating Zeebe diagrams moving forward.
- Ongoing border implementation (@pepopowitz and I have a meeting set for early next week to tackle this.)

Would you prefer to keep this card, or open a new one specifically for Operate/Tasklist screenshot automation to maintain in the backlog? I'm planning to keep up with these teams quarterly to test the waters on capacity so this maintains activity.

**Comment by akeller** [comment]
Let's close this and open new ones with tighter scope - so open a new one for Operate/Tasklist (together is fine if you want to tackle them together).

**Comment by akeller** [comment]
And thank you for calling out the milestones! Great progress here on improving our docs!
