### ISSUE TITLE
Consolidate supported environments (esp. ElasticSearch) for Optimize in C7

### ISSUE THREAD

**Issue by McAlm** [camunda/camunda-platform-docs#1107]
The documentation about Optimize and supported environments for C7 needs more consolidation.
**Supported Environments:** 
[supported-environments](https://docs.camunda.io/docs/reference/supported-environments/) does not list supported ElasticSearch versions for C7 (if it is the same it could be mentioned in the chapter, but currently it is simply not clear.
But can be found here (is not linked from the old C7 docs... : 
[production-distribution-without-elasticsearch](https://docs.camunda.org/enterprise/download/#production-distribution-without-elasticsearch)

**Comment by akeller** [comment]
@toco-cam @RomanJRW can you take a look at this issue? It sounds like the request includes moving some of the information from [the table](https://docs.camunda.org/enterprise/download/#production-distribution-without-elasticsearch) over. Please have your team triage and PR this.

**Comment by RomanJRW** [comment]
Thanks @akeller 👍 
https://jira.camunda.com/browse/OPT-6385 created and in triage 🙂

**Comment by RomanJRW** [comment]
This was completed in https://jira.camunda.com/browse/OPT-6385
