### ISSUE TITLE
I can read about Inclusive Gateway

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-platform-docs#1126]
The diverging inclusive gateway is added to Zeebe in https://github.com/camunda/zeebe/pull/9747 as an external contribution. Of course, all the Camunda Platform 8 need to be aligned and support the feature.

We need to document how users can use the diverging Inclusive Gateway and how it behaves. The behavior is specified in the PR.

Special modeling rules exists, and can be found in:
- https://github.com/camunda/camunda-modeler/issues/3083

Link to product hub:
- https://github.com/camunda/product-hub/issues/214

**Comment by skayliu** [comment]
Hi,@korthout ,@menski  i've docs for this，please check the PR，thank you .
