### ISSUE TITLE
I can easily tell when I've committed a syntax error in .htaccess

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-platform-docs#1135]
[Originally reported in Slack](https://camunda.slack.com/archives/C026U8GBNSW/p1660043063123249).

[This workflow](https://github.com/camunda/camunda-platform-docs/actions/runs/2824629370) timed out due to a syntax error in the .htaccess file, but there was no clear error message to indicate it. 

It looks like the specific failure was on the step that waits for the local server to start up -- [there are no options in that action to present more verbose errors](https://github.com/nev7n/wait_for_response), but we could probably find a library that checks .htaccess for syntax errors, and run that to get a more specific error.

**Comment by jwulf** [comment]
.htaccess tester: https://htaccess.madewithlove.com/

**Comment by pepopowitz** [comment]
I'm closing this issue.

1. I haven't seen any failed builds where this would have been helpful, since the issue was opened.
2. 99% of the problem with redirects is not something that would be caught by a syntax check -- it's an issue specific to the rules that have been created (e.g. a regex that misses a page, or one rule overriding another)

Feel free to re-open if it sees new life.
