### ISSUE TITLE
Referencing pyzeebe in the C8 documentation 

### ISSUE THREAD

**Issue by Hafflgav** [camunda/camunda-platform-docs#1146]
Hi team, 
I wanted to initiate a discussion about which community python client we want to display on our documentation. 
According to this [page](https://docs.camunda.io/docs/apis-clients/community-clients/python/) we are referencing to zeebe_python_grpc. 

I do noticed that our community is also heavily relying on [pyzeebe](https://github.com/camunda-community-hub/pyzeebe). 

Would it make sense to include this client in our list?

**Comment by Hafflgav** [comment]
@jwulf I remember that you have worked together with Nele on pyzeebe some while ago. What is your intention about this? 
Also tagging @akeller and @christinaausley here. ;)

**Comment by akeller** [comment]
Great idea! Including pyzeebe makes sense to me. Also reminds me we have multiple Rust clients, but only one is mentioned.

Can you partner with @christinaausley and @xomiamoore and broaden this to include updates for all the community-supported clients? If you'd rather keep your time investment here small, go ahead and PR this, and @christinaausley can make a new issue with the remaining scope.

**Comment by Hafflgav** [comment]
Awesome @akeller! 😃 
I will create a PR for pyzeebe later this week. Since I am not very familiar with Rust I would leave this hole topic for you @christinaausley. 
If you would like me to take care of this, you could also send me some links to the client repositories which are not yet linked. 👍

**Comment by Hafflgav** [comment]
Hey @xomiamoore, I have created a first PR for the Pyzeebe client. 
Is there any other client we should add to our docu from your perspective. If there is, just let me know which one and I'll handle the rest docu wise. 👍

**Comment by Hafflgav** [comment]
Thanks @christinaausley for creating a new issue for the other clients! 💯 
I am closing this issue for now 👋
