### ISSUE TITLE
Overhaul docu for "How to link a form" 

### ISSUE THREAD

**Issue by Hafflgav** [camunda/camunda-platform-docs#1147]
Within the Web Modeler the user can open up our documentation to learn more on how to link a form. The deep link displayed in the picture blow takes him to [this page](https://docs.camunda.io/docs/components/modeler/bpmn/user-tasks/#user-task-forms) which is not really a good fit.  
![image](https://user-images.githubusercontent.com/30292227/184298231-f9e248c3-80e5-4c7f-b6da-5021630f6c27.png)

Users I have interviewed expected to be able to see an actual example of how they can link a Camunda form. (Similar to what they are able to see when they click on "[How to define conditions](https://docs.camunda.io/docs/reference/bpmn-processes/exclusive-gateways/exclusive-gateways#conditions)") 

Therefore, I am proposing to add more context to this section of the documentation. Are there any concerns @akeller & @christinaausley?

**Comment by akeller** [comment]
Is there a better doc link to send them to? The modeling team is responsible for choosing what doc links they used in the product and as far as I'm aware, we were not consulted on this.

I'd love for you to work directly with @christinaausley on this. I believe she received feedback on this when working on the [Guide](https://docs.camunda.io/docs/guides/utilizing-forms/) (Next steps, not GSG).

**Comment by christinaausley** [comment]
Agreed here. A better link may be https://docs.camunda.io/docs/guides/utilizing-forms/#connect-your-form-to-a-bpmn-diagram.

**Comment by Hafflgav** [comment]
Thanks for your responses! 👍 
I agree with you @christinaausley here. The proposed link is way better. 
Would it be a good idea if we additionally add a GIF to this section?

**Comment by akeller** [comment]
Instead of GIFs, please consider high-quality text instead. GIFs are difficult to make accessible and I'll make more information available about this in the Docs Vision 2.0.

**Comment by Hafflgav** [comment]
Hey @SebastianStamm, 
could you point me to the right place where to change the "How to link a Form" link? 
No need for you to take this over, I just cannot find the file where I would need to make this change. 

Thank you in advance! 💯

**Comment by akeller** [comment]
> could you point me to the right place where to change the "How to link a Form" link?

https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/contextProvider/zeebe/DescriptionProvider.js#L48

But @SebastianStamm would probably know best how or when to anticipate it being released 😄

**Comment by Hafflgav** [comment]
Thanks so much @akeller - I was looking for this repository in the wrong organisation 🤦 
I have created https://github.com/bpmn-io/bpmn-js-properties-panel/pull/741 to change the link already. 

(apparently I am missing out on some rights in this orga, which forced me to create a PR rather not so nicley)

**Comment by Hafflgav** [comment]
The PR has been merged and will be included in the next release. I am going to close this issue now. 👋 
Thanks for all your help @akeller and @christinaausley! 🚀
