### ISSUE TITLE
Automate screenshots

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#115]
For the long-term goal referenced in #110.

We should have an automated process for taking and updating screenshots. Let's use this to discuss relevant tools and methodologies.

**Comment by christinaausley** [comment]
**Timeline**
- **By Nov 11**: Launch draft repository for Operate and Tasklist screenshots.
- **By Nov 18**: Standardize Zeebe screenshots based on approved proposal [here](https://docs.google.com/document/d/1gATpZXVxGiWEF4HfUbpUpQJ8ElyeZROERwiArPX5FRk/edit). Make necessary edits to Operate/Tasklist repo to have it fully functioning.
-  **By Dec 9**: Write out scripts for Operate/Tasklist screenshots.
- **By Dec 16**: Make any necessary final adjustments to Operate/Tasklist repo and screenshots.

**Comment by akeller** [comment]
Thank you for the timeline @christinaausley! This looks great!

**Comment by akeller** [comment]
@christinaausley in terms of the scope or this issue, is anything remaining? Do you have an updated timeline or do you want to create a new issue with a clearer scope about next (or remaining) steps?
