### ISSUE TITLE
Overhaul Microservice Orchestration Guide

### ISSUE THREAD

**Issue by Hafflgav** [camunda/camunda-platform-docs#1162]
The current Microservice Orchestration Guide has some flaws and might need an update. Since it is now going to be featured in the Web Modeler Templates I want to make sure that the guide is as complete as possible.

### Necessary improvements
![image](https://user-images.githubusercontent.com/30292227/184844989-6ca497e1-e11e-48bb-929c-b887823a224b.png)
* The BPMN file does not contain labeled Start- and End-Events
* There is no end event at all
* Only one Java worker is available. Show examples for this guide in more languages / overhaul the GitHub repository. 
* Add more complexity to the diagram so it tells a story (similar to the human task orchestration gsg) 

**Important Note:** Depending on the changes here we need to adapt the template for the Web-Modeler as well.

**Comment by Hafflgav** [comment]
Hey @akeller and @christinaausley, 
while working on the a template for the web-modeler I noticed that there is kind of a gap between the human task and microservice orchestration guide. 
I have noted down a few things which wandered around in my mind. Do you have any feedback on these for me? 😄 

Thanks so much in advance! 
Sorry for keeping you busy :P

**Comment by akeller** [comment]
Hi @Hafflgav. I see the changes you mentioned in the description and addressed each of them below. 

It may be helpful for you to understand some additional context there - the GSG elements are not meant to be comprehensive, but to introduce users to these specific topics as fast as possible. Any Guides in the "Getting started" section are intentionally lean, do not go into detail about modeling (for example), and are designed to be building blocks for other guide content. There may be a fundamental mismatch in goals between how Developer Experience builds and maintains the GSG and how the Onboarding Team would like to iterate on them.

I would argue a pre-built template doesn't need to match the experience in docs but could be considered an opportunity to model a more advanced process by hand with a separate Guide. 

> - The BPMN file does not contain labeled Start- and End-Events

To me, this is a nitpick. If you want to follow best practices for good modeling, I'm all for it, but the service task name should be updated as well.

> - There is no end event at all

An end event is not pictured in the screenshots but included in the steps. We made a maintenance and accessibility choice to not include an extensive amount of images in the Guides section, particularly the GSG. We should focus on high-quality text and supplement with images if necessary. 

> 7. Add an end event by dragging one from the palette, or by clicking the end event when the last service task in your diagram has focus. Make sure there is an arrow connecting the service task to the end event.

> - Only one Java worker is available. Show examples for this guide in more languages / overhaul the GitHub repository.

We accept PRs 😉, but someone will need to maintain additional worker examples. 

> - Add more complexity to the diagram so it tells a story (similar to the human task orchestration gsg)

The goal of this GSG was specifically to **not** introduce more complexity but to introduce the basics in the quickest way possible. I would recommend considering a separate Guide in the "Next steps" section if you'd like to introduce more advanced modeling or a larger example.

**Comment by HanselIdes** [comment]
Hi @akeller and @Hafflgav,
I think we do need to review the role of the GSG within the context of the [User Onboarding Vision](https://confluence.camunda.com/display/HAN/User+Onboarding+Vision)

Thoughts:
1. The product provides users with a prebuilt template and in-app guidance based on their desired use case. Guidance begins as no-code Appcues flows until they prove successful and we promote them to pro-code with engineering work.
2. The GSG takes the user on a step-by-step journey to create a trivial diagram based on their desired use case
3. The Academy shows the user how to create a non-trivial diagram based on their desired use case

We have to figure out where the GSG fits in:
a) As an alternative to the in-app onboarding guidance with the prebuilt template. This gives us more flexibility to make a more meaningful basic template, but adds maintenance costs and may be confusing
b) To describe how to recreate the prebuilt template and achieve the first strike. This means the in-app experience is tied to the GSG, which reduces confusion and maintenance but maintains dependencies between the Onboarding and DevEx teams

If we want to add more advanced features, that makes sense in an intermediate template that's aligned with the Academy courses.

For the specific feedback here, I agree with Amara on most of them.
> The BPMN file does not contain labeled Start- and End-Events
> There is no end event at all

First-time users shouldn't have to think about BPMN best practices, which should be reserved for after first strike.

> Only one Java worker is available. Show examples for this guide in more languages / overhaul the GitHub repository.
> Add more complexity to the diagram so it tells a story (similar to the human task orchestration gsg)

This is more appropriate for the intermediate example, in collaboration with the Academy team.

I hope this helps us stay aligned on the right changes to make in the documentation.

~Eric

**Comment by HanselIdes** [comment]
As an aside:

IMO, the GSG _should_ be opinionated about which way to achieve a task. This helps reduce the amount of text.

> Add an end event by **dragging one from the palette, or by clicking the end event when the last service task in your diagram has focus**. Make sure there is an arrow connecting the service task to the end event.

I propose:

> Append an end event by selecting your service task and clicking the end event icon. 

As this directly affects the Modeler, which pattern do you want to prioritize teaching @christian-konrad?

**Comment by Hafflgav** [comment]
So to conclude here we can say that the current microservice orchestration guide should stay as it is for the time being and that we would rather like to create a new intermediate version in collaboration with the Academy team. 

@HanselIdes do you want me to create a new issue for this in our team project?
