### ISSUE TITLE
update community clients

### ISSUE THREAD

**Issue by christinaausley** [camunda/camunda-platform-docs#1178]
Alongside https://github.com/camunda/camunda-platform-docs/issues/1146#issuecomment-1216267466, ensure community clients are updated with accurate ownership and repos/docs.

@xomiamoore Adding you here in case I need to confirm ownership of these community clients. Will follow up!

**Comment by xomiamoore** [comment]
Hey Christina -- a few things to look into:

* [This list](https://github.com/orgs/camunda-community-hub/repositories?q=client&type=all&language=&sort=stargazers) is everything with the word "client" in the repo name, sorted by Stars. In total there are 24 and quite a few that are not included in the docs currently.
  * Do we want to include every single client, or only the more popular ones?
* Does the docs page breaking down each community client and their owner make sense to include? I'm wondering if it would be more helpful to just link to the GitHub repo for their current ownership and status vs. having to update the docs if there's a change. Thoughts?

**Comment by akeller** [comment]
Just a quick chime in from me - narrow the list to C8 clients @xomiamoore. 

Other than that, you make a great point about presenting this info in the docs to be maintainable (and sustainable!).

**Comment by xomiamoore** [comment]
Awesome, can do @akeller. 

(Do we not have an equivalent page for C7 clients? If not, should we? I'm sure this is a separate issue if so!)

**Comment by akeller** [comment]
Good 1:1 question, but out of scope for these docs since they just cover C8.

**Comment by christinaausley** [comment]
Thank you @xomiamoore! I've added a a few materials and adjusted the wording so we don't have to update naming for maintainers and can make this more evergreen. Feel free to take a look at the [PR](https://github.com/camunda/camunda-platform-docs/pull/1257) and see if I've missed anything.

**Comment by christinaausley** [comment]
Closing as this PR is merged 👍
