### ISSUE TITLE
Audit and update `/howtos/` 

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#1179]
Our "How Tos" or what I've recently called our "docs on docs" are a bit stale in some places. 

Things to update:

- [x] Camunda Cloud is now Camunda Platform 8
- [x] Documentation handles components with fixed releases and continuous releases
- [x] Introducing the PR checklist template
- [x] Identifying our docs reusable components
- [x] @christinaausley any updates to the cheat sheet and style guide? Would you rather point to the style guide on camunda.com?
- [x] Anything else that either no longer applies

**Comment by christinaausley** [comment]
@akeller Happy to review the style guide and ensure it's updated according to our latest version -- will launch a PR with any revisions. Just marked it on my calendar to continuously review this on a monthly basis 👍

**Comment by akeller** [comment]
I did some of this in #1281, but I'm not sure how much detail we want to go into for "identifying our docs reusable components".

**Comment by christinaausley** [comment]
Style guide updated in https://github.com/camunda/camunda-platform-docs/pull/1191

**Comment by akeller** [comment]
Given that we only have 1 reusable component, I'm going to close this and call it done. We can revisit in the future with a new issue.
