### ISSUE TITLE
Grafana dashboard image is too small to be useful

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#1190]
The [Grafana dashboard image](https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/metrics/#grafana) is too small, and in reality, the dashboard is much longer than this screenshot implies.

@christinaausley in the screenshot automation you are working on, is this included? My gut says no. 

I'd love to see a better description of the types of reports and info available on this dashboard in the text. A larger image would be great too. Although, it may be easier to add more granularity to the [README](https://github.com/camunda/zeebe/tree/main/monitor) for monitoring, which makes this issue a little bit more open-ended for what the definition of "complete" is. 

Big thanks to @falko for pointing this out!

**Comment by akeller** [comment]
This may be a good opportunity to work with the SREs to see what information they use regularly and what information should be available on the docs page vs. the GitHub README. 

@christinaausley I'm going to assign this to you, but we can talk more about it in our 1:1. For now, this will go in the backlog.

**Comment by akeller** [comment]
@christinaausley after speaking with Immi, it sounds like Zell and Nicolas own this as the Zeebe team so they would be better to approach with any questions you have on this.

**Comment by christinaausley** [comment]
Thank you @akeller ! Planning to take a closer look at this as soon as I'm back from FTO. If that blocks anything or causes any issues, let me know and I'll hop on this tomorrow.

**Comment by akeller** [comment]
You could even look at this as a Q4 item.

**Comment by akeller** [comment]
@christinaausley is there any active work going on here? Do you need any help with scoping?

**Comment by christinaausley** [comment]
Working with @oleschoenburg on this as the image is outdated as well.

Discussing with @oleschoenburg today, but he'll plan to update the image accurately and we'll discuss the following:

1. The text alongside such images.
2. Sizing the images.

Both of these I'll update in the README file accordingly.

**Comment by christinaausley** [comment]
Note that after discussing today via Zoom, @oleschoenburg is working to update here (with some discussion on screenshot automation?)

I'll plan to work with Ole on the accompanying text, and [potential intractability](https://grafana.dev.zeebe.io/dashboard/snapshot/7Acu5ka26AI06rNPQjKO1aMwcR9syv5n?orgId=0&from=1681483857436&to=1681484757437). I'll plan to update the README accordingly following changes.

**Comment by christinaausley** [comment]
See https://github.com/camunda/camunda-platform-docs/pull/1982 for changes across versions -- this is about ready for merge.
