### ISSUE TITLE
docs.camunda.io is not on Bing

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#1200]
We have some issues with SEO, or in the case of Bing, lack of even appearing on searches. Based on Bing Webmaster Tools this appears to be happening since July 7th where _very_ limited data appears since. I'm unsure what's happening here and we've done **many** docs releases since then. There are a few high SEO issues, including #1199 and #1198. I'm unsure if fixing these issues will allow Bing to show docs.camunda.io in searches. 

"Camunda docs" returns no results for docs.camunda.io on Bing.

"Camunda docs" returns results for docs.camunda.org first, then docs.camunda.io on Google:

![image](https://user-images.githubusercontent.com/1051363/186977909-e14d7952-6576-4e70-baf3-c9a5e23ee2da.png)

Notice the description is part of the Self-Managed page description. This is misleading or incorrect. I do like that it includes a link to the introduction part of the Guides section. I also like that there are links to the other top nav header links.

"Camunda Platform 8 docs" returns no result for docs.camunda.io on Bing.

"Camunda Platform 8 docs" returns the top nav structure and some overview pages on Google:

![image](https://user-images.githubusercontent.com/1051363/186978399-d8957874-4799-40bc-830c-e988b405acd7.png)

Does anyone have any ideas what is going on here? Anything we could try?

**Comment by akeller** [comment]
Bing Webmaster Tools does show a sitemap, but I submitted https://docs.camunda.io/sitemap.xml again today to see if this helps.

**Comment by akeller** [comment]
Looks like this is happening to other folks, looks fine on Google, but not fine on Bing.

https://www.jessesquires.com/blog/2022/03/25/my-website-disappeared-from-bing-and-duckduckgo/
https://www.jessesquires.com/blog/2022/07/25/my-website-disappeared-from-bing-and-duckduckgo-part-2/
> To recap: I did nothing, Bing de-indexed my website, Bing said I violated its guidelines, I continued to do nothing, Bing restored my website, and now everything seems (mostly) fine. 

https://io.bikegremlin.com/28530/microsoft-bing-serp-gone-overnight/

**Comment by akeller** [comment]
I submitted a support request with Bing. Based on their automated email they will respond in 10 days.

**Comment by akeller** [comment]
I’ve restored some of the docs.camunda.io pages to Bing search by submitting individual URLs for each section of the docs site. Despite resubmitting the sitemap it doesn’t seem to have the impact the individual URLs seem to have eventually. I can automate this, which I may try to do, and at least get some of the landing pages we have surfacing.

We have a plan to resolve the “SEO issues” Bing identified, but I don’t think they are preventing visibility on Bing results. They also haven’t responded to my request from Aug 26th. GitHub say that was 12 days ago. Maybe it's 10 business days.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/1051363/189011336-15e1c178-4f2f-4624-aad7-152df0b10c2c.png">

![image](https://user-images.githubusercontent.com/1051363/189011506-e1acf0ec-c457-4712-b63e-b7f04a4cb863.png)

<img width="980" alt="image" src="https://user-images.githubusercontent.com/1051363/189011653-44202eda-49b0-424a-8218-642681b3d8fb.png">

**Comment by pepopowitz** [comment]
@akeller let me know if you want to pair on automating the individual submissions

**Comment by akeller** [comment]
Thanks Bing.

![Image](https://github.com/camunda/camunda-platform-docs/assets/1051363/1fd40945-cc6d-4df0-b255-2b185086be2d)
