### ISSUE TITLE
Document setting model deployment connection parameters for a self-managed deployment with Identity from Desktop Modeler

### ISSUE THREAD

**Issue by rob2universe** [camunda/camunda-platform-docs#1283]
https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/connect-to-camunda-cloud/ only covers Saas. 
It should also cover how to set the parameter for a self-managed deployment with identity enabled.
Where to get the client Id and secret? What to set fore OAuth URL and Audience?
How doe sit differ if Identity is not enabled in self-managed?

**Comment by akeller** [comment]
@rob2universe I may not be following this correctly.

Are you looking for how to connect Self-Managed Web Modeler? Or Desktop Modeler to Self-Managed? Or both? 😅

**Comment by rob2universe** [comment]
This is about desktop modeler. Updated title to be clearer. 

Going forward I assume the web modeler in self-managed will be configured to correctly deploy to the self-managed cluster.

**Comment by akeller** [comment]
@camunda/modeling-dev is this something you are aware of? Do you have another issue I can link to?

**Comment by barmac** [comment]
Note that oAuth token is not used in C8 for authentication in the gateway: https://github.com/camunda/product-hub/issues/120
I suspect that documenting token retrieval with Desktop Modeler could give a false sense of security until the oauth authentication in the gateway is implemented.

**Comment by barmac** [comment]
Or we should explicitly state that the feature is implemented only via community extension: https://github.com/camunda-community-hub/zeebe-keycloak-interceptor
