### ISSUE TITLE
Redesign CSS and branding styles/colors

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#1290]
Full custom Camunda branding style/colors incorporated into CSS in an easy, reusable way. Right now this is a mix of default Docusaurus and hastily pulled together "hacks". 

From an accessibility lens, it would be good to confirm we have no contrast issues.

**Comment by VoidCupboard** [comment]
Hi! I would love to work on this issue if you can explain a bit more

**Comment by akeller** [comment]
Hi @VoidCupboard, this is actually quite a large topic that requires some design work and consideration that my team and I aren't prepared to support at this time. Thanks for offering to work on this, though!

**Comment by VoidCupboard** [comment]
Ah makes sense, no problem @akeller :)

**Comment by akeller** [comment]
This feels stale. Closing.
