### ISSUE TITLE
Clarify m2m token usage for claimTask

### ISSUE THREAD

**Issue by aleksander-dytko** [camunda/camunda-platform-docs#1327]
###User problem
Some users, may not know that the JWT token is meant for the m2m communication and issuing it per application, not per user. 
See: https://forum.camunda.io/t/how-to-create-authtoken-to-access-tasklist-api-incase-of-self-managed-deployment/38274/13?u=aleksander-dytko

###Desired solution
Add information about m2m token to https://docs.camunda.io/docs/next/apis-clients/tasklist-api/mutations/claim-task/ - that the user, who generated token is not assigned to it.

**Comment by johanwelgemoed** [comment]
For 8.0.x versions
Reach out @sdorokhova about grapnql doc updates as well.

**Comment by johanwelgemoed** [comment]
@aleksander-dytko I made the comment above that this is for 8.0.x versions, but I assume we need this on all versions from 8.0 onward as well right? (ie. will need to do same for 8.1.x docs)

**Comment by aleksander-dytko** [comment]
> @aleksander-dytko I made the comment above that this is for 8.0.x versions, but I assume we need this on all versions from 8.0 onward as well right? (ie. will need to do same for 8.1.x docs)

@johanwelgemoed yes - from the 8.0 onwards ;)

**Comment by johanwelgemoed** [comment]
Update to also clarify confusion on when assignee is optional and when not

**Comment by johanwelgemoed** [comment]
Also update Tasklist GraphQL schema file for future versions once text finalised
