### ISSUE TITLE
Fix links for broken java client samples source code

### ISSUE THREAD

**Issue by menski** [camunda/camunda-platform-docs#1340]
With https://github.com/camunda/zeebe/pull/9513 the java client samples where removed from the Zeebe repository and moved to the community project https://github.com/camunda-community-hub/camunda-8-examples/pull/3.

The nested pages of https://docs.camunda.io/docs/next/apis-clients/java-client-examples/ contains links to the source code which are now broken and should point to the new community project instead.

**Comment by VoidCupboard** [comment]
Hi! Can I work on this issue?
