### ISSUE TITLE
Link to  zeebe-ssl-certificate flag in the `Deploy your first diagram` guide

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-platform-docs#1346]
### What to do?

Link to [zeebe-ssl-certificate flag](https://github.com/camunda/camunda-platform-docs/pull/1316) from the [`deploy your first diagram` guide](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/connect-to-camunda-cloud/)

### Why to do it?

Users in self-managed setups might fail to deploy diagrams from desktop modeler because they have not configured ssl certificate. Probably they would try to find out how to deploy reading [this guide](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/connect-to-camunda-cloud/).

I think a brief link to the ssl certificate flag in this guide would be helpful to overcome this.

**Comment by MaxTru** [comment]
WDYT @barmac ?

**Comment by barmac** [comment]
I think this makes sense.

**Comment by barmac** [comment]
I can imagine this as a note on top: "In case you want to deploy to Camunda Platform 8 Self-Managed with a custom SSL certificate, [there is a flag which allows to configure it](https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/flags/#zeebe-ssl-certificate).".

**Comment by MaxTru** [comment]
Do you know, if this is the default case now for customers that have self-managed with Identity set-up? Or will our self-managed installation with Identity "just work"?

**Comment by barmac** [comment]
I don't know, I haven't tried Identity setup yet. There is however an issue on deployment problems for this: https://github.com/camunda/camunda-modeler/issues/3152

**Comment by MaxTru** [comment]
I think we should try this typical end-2-end use-case first. This will allow us to better organize our Docs.

**Comment by rob2universe** [comment]
https://github.com/camunda/camunda-modeler/issues/3152 also occurs without ssl

**Comment by nikku** [comment]
@akeller Something along these lines? https://github.com/camunda/camunda-platform-docs/pull/2052

**Comment by akeller** [comment]
Do you know if we need to mention self-signed certs specifically, or would this apply to any cert? Self-signed certs can make enterprise IT team nervous.

IMO the proposed PR meets the needs and scope of this issue and would close it out.

**Comment by nikku** [comment]
> Self-signed certs can make enterprise IT team nervous.

What exactly makes who nervous? Most enterprise IT will have some sort of self-signed root in their chain from which all sorts of trust is inherited. We're seeing this from many customers, across the board: Self-signed root + intermediate + server certificates derived from that.

**Comment by nikku** [comment]
Potential improvement: https://github.com/camunda/camunda-platform-docs/pull/2052/commits/581988583625c812846b8f237a00686d2083c9a6.

**Comment by akeller** [comment]
In my experience, getting a cert from a trusted CA is strongly preferred. Self-signed can imply the connection is insecure. Even internally at Camunda, IT asks us not to use self-signed certs. This may be new or due to an update in security scanning tools. This is why I'm asking, just to clarify. 

I like your improvement! Gets us away from language that potential customers may focus on as supporting an "insecure" path.

**Comment by nikku** [comment]
Will update the PR (backport changes where necessary). Let's improve this bit and close this issue.
