### ISSUE TITLE
Mention output mappings for none end events are supported

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda-platform-docs#1362]
## Description

The documentation for None-events currently mentions that end events do not support variable output mappings. With the merge of https://github.com/camunda/zeebe/pull/10618 this is now supported. This text should be changed to reflect this change.

## Should go live
8.2 release

**Comment by AnuragThePathak** [comment]
Hi, will it be fine if I change the line to something like
> Start, intermediate, and end none events can have [variable output mappings](https://github.com/camunda/camunda-platform-docs/blob/9f6c6577bed43eec90e26e7b4b5cc373bfe883f8/versioned_docs/version-1.3/components/concepts/variables.md#output-mappings).
>

**Comment by remcowesterhoud** [comment]
Hi @AnuragThePathak! I think we should change your suggestion a little bit. It doesn't make sense to me to list all the None events specifically.

Personally I'd change it to something like:

> All none events can have [variable output mappings](https://docs.camunda.io/docs/next/components/concepts/variables/#output-mappings).

For start events, this is often used to initialize process variables.
