### ISSUE TITLE
Element Template Page missing from C8 sidebars (8.0, 8.1, Next)

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#1382]
Looks like `https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/element-templates/` isn't part of the sidebars, which is why the navigation doesn't show up on the side. In fact, it looks like this page is not in the sidebars for any C8 version.

```
{
      "Element templates": [
        "components/modeler/desktop-modeler/element-templates/about-templates",
        "components/modeler/desktop-modeler/element-templates/configuring-templates",
        "components/modeler/desktop-modeler/element-templates/using-templates",
        "components/modeler/desktop-modeler/element-templates/defining-templates",
        "components/modeler/desktop-modeler/element-templates/additional-resources"
      ]
 },
```

We need to add `components/modeler/desktop-modeler/element-templates/element-templates`.

Let me open another PR @nikku and I'll get this fixed for you today. Great catch! And so sorry we didn't notice this sooner.

_Originally posted by @akeller in https://github.com/camunda/camunda-platform-docs/issues/1377#issuecomment-1276199267_

**Comment by pepopowitz** [comment]
@akeller I think that #1386 makes this a non-issue, right?

**Comment by akeller** [comment]
Yes, thank you @pepopowitz!
