### ISSUE TITLE
HTO GsG: Fix inconsistency of process variables

### ISSUE THREAD

**Issue by Hafflgav** [camunda/camunda-platform-docs#1412]
### Feedback: 
The HTO documentation features the variable "meal" which is sometimes written small sometimes big. Since Camunda is key sensitive this will lead to an incident. 
This Feedback was collected during a guest lecture at the TU Dortmund. 

### Occurrences: 
Capitalised "Meal":
<img width="834" alt="image" src="https://user-images.githubusercontent.com/30292227/196672396-efef4d0d-1ae8-47cc-80ad-dc1dd2f21ac7.png">
Small "meal":
<img width="482" alt="image" src="https://user-images.githubusercontent.com/30292227/196672466-d8763cda-9e8d-4678-955d-e075ce0cd1ba.png">

**Comment by Hafflgav** [comment]
As variables are usually written without a capitalised starting letter I am going to name it "meal" instead of "Meal". By doing so I do not need to replace the whole screenshot either.

**Comment by Hafflgav** [comment]
PR Comments resolved - waiting for it to be merged

**Comment by akeller** [comment]
Looks like the corresponding PR was merged. Can we close this issue now?

**Comment by Hafflgav** [comment]
Oh no, thanks for pointing this out @akeller. I truly thought that I have had closed all of the issues. 
Doing so now :)
