### ISSUE TITLE
Add releases and end of maintenace dates to announcement page

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-platform-docs#1427]
We should announce our releases here: https://docs.camunda.io/docs/reference/announcements/
And add a scheduled out of maintenace date for the releases + also mention when certain versions go out of maintenance e.g. 1.3

Similar to  https://docs.camunda.org/enterprise/announcement/

Slack thread https://camunda.slack.com/archives/C02UMKN3DTL/p1666598658371359

**Comment by menski** [comment]
Quick win:
- List all releases since 1.0 including next future release 8.2 to announce scheduled release data
- mention the end of maintenance in releases

**Comment by akeller** [comment]
Will fix it in #1801 by DevEx.
