### ISSUE TITLE
Review Postman repositories 

### ISSUE THREAD

**Issue by aleksander-dytko** [camunda/camunda-platform-docs#1457]
**Context**
Currently, we have a [Postman workspace](https://www.postman.com/restless-shuttle-19836/workspace/camunda-platform-8/) and [Github repository](https://github.com/camunda-community-hub/camunda-8-api-postman-collection) with examples for specific component API in Postman file. For now it's a community project, but in the long term would be great if we can include it in our docs. 

**Expectation**
I would appreciate it if someone could review content of both repositories

**Comment by jwulf** [comment]
I couldn't get it to work.

**Comment by christinaausley** [comment]
I'll take a look at this either tomorrow or Monday for review 👍

**Comment by christinaausley** [comment]
Note that both of these resources have been reviewed.

@jwulf -- where did you run into issues? Do you want to schedule a call to discuss?

**Comment by akeller** [comment]
@aleksander-dytko is there anything else you are looking for from my team here? Can we close this out?

**Comment by aleksander-dytko** [comment]
@akeller no, @christinaausley review repositories and I forgot to close the issue here. Thanks!
