### ISSUE TITLE
Document workaround to use self-signed certificates to connect to elasticsearch

### ISSUE THREAD

**Issue by menski** [camunda/camunda-platform-docs#1490]
We want to improve this setup with this epic https://github.com/camunda/product-hub/issues/583

Until then we should document the workaround needed to get this working. Examples of this workaround can be found in https://github.com/camunda/camunda-platform-helm/issues/473

**Comment by johanwelgemoed** [comment]
Most likely need to be updated here : https://docs.camunda.io/docs/next/self-managed/operate-deployment/operate-configuration/#elasticsearch
