### ISSUE TITLE
Update documentation of our BPMN symbol coverage

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-platform-docs#1506]
Since we introduced today (Nov 15) support for all BPMN symbols for strategic modeling in Modeler, we need to update our [documentation on symbol coverage](https://docs.camunda.io/docs/next/components/modeler/bpmn/bpmn-coverage/) to make it clear which symbols are supported for modeling, and what is the supported subset for execution.

Easiest could be to change text from `The following BPMN elements in green are supported.` to `The following BPMN elements are supported by Modeler. The elements in green are supported for execution.`

**Comment by akeller** [comment]
@christian-konrad is this something your team will take care of?

**Comment by christian-konrad** [comment]
@akeller yes :)

**Comment by nikku** [comment]
Will be addressed via https://github.com/camunda/camunda-platform-docs/pull/1540.

**Comment by nikku** [comment]
Backport to be merged after next modeler minor release: https://github.com/camunda/camunda-platform-docs/pull/1541
