### ISSUE TITLE
Add "What's a connector" to docs

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-platform-docs#1507]
https://docs.camunda.io/docs/components/connectors/introduction-to-connectors/ is missing a quick intro what makes a connector (e.g. like in https://camunda.com/blog/2022/07/a-technical-sneak-peek-into-camundas-connector-architecture/).

Latest picture e.g. here. https://docs.google.com/presentation/d/1F_xr6LSmut84up_OkyEwgGh9JSkQuhyqmTihM0TlavE/edit#slide=id.g15a5b1f60a9_0_3408

![grafik](https://user-images.githubusercontent.com/1217596/201960052-3cd8b60c-210e-451f-8355-7b694e2b8396.png)

**Comment by tmetzke** [comment]
I think we can play this on different levels of detail in different parts of the documentation. Something like this might suffice for the general "how does this work" use case. But more detailed views might be interesting in Self-Managed, for example, detailing where secrets are coming from and where the Connector functions run.

**Comment by akeller** [comment]
Closing this issue as it's a bit stale. Please see this [doc](https://docs.google.com/document/d/1VB_cDTaNfdyT6xyHj_YlYJfW76Rt76LYsls7AsIqpZQ/edit#heading=h.cv58mxb2xmxo) as part of https://github.com/camunda/product-hub/issues/1005.
