### ISSUE TITLE
Document use case for fail job with variables

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-platform-docs#1508]
Since `8.2.0-alpha1` users can [pass variables along when failing a job](https://github.com/camunda/zeebe/issues/9404). This is also documented in the job-worker concept where we discuss [completing or failing jobs](https://docs.camunda.io/docs/next/components/concepts/job-workers/#completing-or-failing-jobs).

> When Completing or failing jobs with [variables](https://docs.camunda.io/docs/next/components/concepts/variables/), the variables are merged into the process at the job's associated task.
>
> - When Completing a job the variables are propagated from the scope of the task to its higher scopes.
> - When Failing a job the variables are only created in the local scope of the task.\

Currently, that documentation only describes the behavior. Not why a user would want to do this. We should clarify why a user might want to send along variables when failing a job:
- may help users to analyze the incident when failing the job with `retries: 0` by allowing them to provide additional details along with the fail job command
- may help users to continue where they left off when retrying the job. I.e., the job was completed partially, and the job worker is able to skip parts of the work but needs to know where to continue.

**Comment by menski** [comment]
@menski keep this in mind of 8.2 release
