### ISSUE TITLE
Automagically move items to "Done" on Developer Experience board when merged

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#1539]
Most items move manually across the [Developer Experience board](https://github.com/orgs/camunda/projects/27).

If a PR is merged or an issue is closed, the item should appear in the "Done" column. 

## Implementation Suggestions

- See [these GitHub docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges) on how to trigger a workflow when a PR is merged.
- ~[This GitHub doc](https://docs.github.com/en/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards) _might_ describe an existing action we can use to move the card over, although when we originally set up [the sync-board workflow](https://github.com/camunda/camunda-platform-docs/blob/main/.github/workflows/sync-board.yaml) we didn't use this, and I don't remember why.~ 
   - @christinaausley and I dug into this a bit to see if we could get a quick win, and we were reminded why we can't use this workflow: 
      - It [looks for a project based on the current repository or the repository's owner](https://github.com/alex-page/github-project-automation-plus/blob/main/src/generate-mutation-query.js#L14-L18), and the Developer Experience project does not exist in either of those places. See screenshot for graphql query that simulates what the code in the workflow is trying to find (and note that neither of the collapsed results are the Developer Experience project):
      <img width="1159" alt="image" src="https://user-images.githubusercontent.com/1627089/208755626-bd489bf5-d1a5-4375-bcfc-a6b6d356d32d.png">
      - This results in the error `Could not find the column "✅ Done" or project "Developer Experience"` when [running the workflow](https://github.com/camunda/camunda-platform-docs/actions/runs/3743622327/jobs/6356000154).
- If we need to write the action ourselves, see [the sync-board workflow](https://github.com/camunda/camunda-platform-docs/blob/main/.github/workflows/sync-board.yaml) for hints on how to update the status on a board item. More specifically:
   - [Define the org and project](https://github.com/camunda/camunda-platform-docs/blob/main/.github/workflows/sync-board.yaml#L17-18)
   - [Get the project, status field, and status IDs](https://github.com/camunda/camunda-platform-docs/blob/main/.github/workflows/sync-board.yaml#L20-L43)
   - [This part](https://github.com/camunda/camunda-platform-docs/blob/main/.github/workflows/sync-board.yaml#L49-L58) will need to be rewritten - in sync-board it returns the item ID from a mutation; we'll need to _query_ for the item, instead. See specific query below.
   - [Set the status field](https://github.com/camunda/camunda-platform-docs/blob/main/.github/workflows/sync-board.yaml#L63-L82).

### Query for getting the item ID of a PR within a project

`$prID` can be retrieved [from the workflow environment](https://github.com/camunda/camunda-platform-docs/blob/main/.github/workflows/sync-board.yaml#L47) with `github.event.pull_request.node_id`

```graphql
query pr($prID: ID!) {
  node(id: $prID) {
    ... on PullRequest {
      title
      author {
        login
      }
      projectItems(first: 10) {
        nodes {
          id
          project {
            number
          }
          fieldValues(first: 10) {
            nodes {
              ... on ProjectV2ItemFieldSingleSelectValue {
                optionId
                name
              }
            }
          }
        }
      }
    }
  }
}
```

An example response: 

```json
{
  "data": {
    "node": {
      "title": "[WIP] feat: set up regression tests",
      "author": {
        "login": "pepopowitz"
      },
      "projectItems": {
        "nodes": [
          {
            "id": "PVTI_lADOACVKPs4ADm-7zgDqwE0",
            "project": {
              "number": 27
            },
            "fieldValues": {
              "nodes": [
                {},
                {},
                {},
                {},
                {
                  "optionId": "e34d6107",
                  "name": "🏗 In progress"
                }
              ]
            }
          }
        ]
      }
    }
  }
}
```

The value we'll want to capture from the response is `data.node.projectItems.nodes[].id`.

To be cautious, we can confirm that it's the `data.node.projectItems.nodes[]` with `project.number === 27` (which is the number of the DX board project). The sync-board job defines this value as an environment variable.

**Comment by akeller** [comment]
@pepopowitz we talked about this one last week. Do you want to snag it and add more details?

**Comment by akeller** [comment]
Manually moving this to status `Done`

**Comment by akeller** [comment]
@pepopowitz FYI, this issue was closed but didn't automatically move to `Done`. Not sure if this is expected or an edge case.

**Comment by akeller** [comment]
> But then I thought about how many of the issues that I open have more than one PR associated with them....and I don't think I'd want those to auto-move-to-done. (TBH I wouldn't want them to auto-close, either, which probably means I wouldn't want to link the PR to the parent issue.)

Good point. I'm fine moving issues manually since they can represent multiple PRs. I'm happy to update the original scope to be just PRs if we want to call this done. WDYT?

**Comment by pepopowitz** [comment]
It also might be pretty straightforward -- [we can trigger on issue:closed](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues); and do something similar to what we're doing for pr:merged to find the associated board item, and move it to done.

**Comment by akeller** [comment]
It was mostly the PRs that were the issue because there were so many of them! But we can add a new issue for issues 😆 and pop it in the backlog.
