### ISSUE TITLE
Remove XML representation from BPMN docs 

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-platform-docs#1587]
## Description

Currently, the documentation of BPMN elements contains a [XML representation](https://docs.camunda.io/docs/next/components/modeler/bpmn/service-tasks/#xml-representation). 

We don't consider the XML useful anymore because we assume that our users use the Camunda Modeler (or Web Modeler) and don't write the XML by hand. 

Developers of Modeling tools are not the target of this documentation.

**Comment by akeller** [comment]
Please work with @christinaausley if you need any help from DevEx 🚀

**Comment by ingorichtsmeier** [comment]
Hi @saig0,

to build the best possible tool to convert bpmn diagrams from Camunda 7 to Camunda 8 it is still important to get the XML configuration of each element at a glance. 

Where should the information stay in the future? 
Maybe in a dedicated Reference section? (@akeller the reference section, again...)

**Comment by saig0** [comment]
> to build the best possible tool to convert bpmn diagrams from Camunda 7 to Camunda 8 it is still important to get the XML configuration of each element at a glance.
>
> Where should the information stay in the future?

@ingorichtsmeier interesting point. 

What about using the Camunda modeler? 
If you model the process in the Camunda modeler for Camunda Platform 8 then you can view the XML in the modeler tab. 

I assume that the migration is an edge (and temporary) use case. Do we really need to put the XML part in our docs?

**Comment by ingorichtsmeier** [comment]
@saig0, the modeler shows only elements that are filled with content. From time to time I need to see, what is possible and allowed without trial and error. Therefore, a reference is required.

Customers sometimes get the wildest ideas about process behavior, and the XML reference and examples are a proven way to see if they can be achieved or not.

I've had a good experience with the Camunda Extensions like here: https://docs.camunda.org/manual/7.18/reference/bpmn20/tasks/user-task/#camunda-extensions, but also the other parts of these pages.

**Comment by ingorichtsmeier** [comment]
Hi @megglos,

I think in our distributed platform environment, the Zeebe engine interprets and defines the BPMN extensions. 

Zeebe is the leading component and should document the XML structure somewhere. 

Maybe in a README in the Github repo and link it in the docs.

From time to time, users have to look up what is allowed in the Zeebe engine and what is not possible.

**Comment by akeller** [comment]
I'll do a bit more digging with this issue.

This documentation space is now _the_ documentation for Modeler for C7 and C8 (SaaS and SM). 

I need some help from PM to understand how many users are hand writing XML or referencing the XML. How much would a SaaS user care about XML?

> From time to time, users have to look up what is allowed in the Zeebe engine and what is not possible.

Is the XML in the Modeler section the best way to achieve this? Should we consider some other documentation experience? An example could help here.

**Comment by ingorichtsmeier** [comment]
Hi @akeller,

when I have to look up some not so well known SQL statement for my relational database, I jump to their docs and look for the SQL reference. Usually I find the statements alphabetically ordered and dive into the syntax and the explanation.

The BPMN extension is (at least for me) the same as the SQL implementation for a database like PostgresQL, MySQL or Oracle. (Some kind of Reference documentation). 

90% are well known and often used. The rest is rarely used, and I need to look up the details from time to time.
