### ISSUE TITLE
Document changes in Hot backups for Operate and Tasklist

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda-platform-docs#1609]
* Main URL entry is renamed to `backups`
* Make endpoints description up-to-date
* Document that the endpoint is exposed on management port
* Document the ENV var to configure the snapshot repository

**Comment by akeller** [comment]
> Main URL entry is renamed to backups

Is this considered a breaking change?

**Comment by sdorokhova** [comment]
@akeller 
>Is this considered a breaking change?
Yes, in terms that if anybody used the old URLs, this won't work anymore. There may be more breaking changes, if we think. In the endpoints that existed before and changed now. Do we need to mention this explicitly?
We had a disclaimer before that Backup API is a subject to change. So no promises for backward compatibility were done before.

**Comment by akeller** [comment]
@christinaausley can you assist @sdorokhova with making this more obvious that this is a breaking change?

**Comment by akeller** [comment]
@sdorokhova if I understand correctly, moving forward, we will have backward compatibility, right? I went ahead and merged the PR. 

If my understanding is not correct, we'll need to launch a PR to update this and make it clear.

**Comment by sdorokhova** [comment]
Hi @akeller , I'm not really sure what you mean by "moving forward, we will have backward compatibility". If they started using the API in 8.1 , it won't work after update to 8.2. They would need to adjust there API usage (different endpoints, different responses). But with further version (8.3 etc.) we will aim to be backward compatible.

**Comment by christinaausley** [comment]
@sdorokhova Mind if I pop some time on your calendar to discuss? Happy to launch a PR for clarity on my end.
