### ISSUE TITLE
Error Boundary events with errorCodeVariable and errorMessageVariable

### ISSUE THREAD

**Issue by lzgabel** [camunda/camunda-platform-docs#1637]
With https://github.com/camunda/zeebe/pull/11388, Zeebe now supports Error Boundary events with`errorCodeVariable` and `errorMessageVariable`. Allow specifying specific variable names for the `errorCode` and `errorMessage` in the process model (BPMN). For example, `errorCodeVariable: 'errCode'` would end up creating a process variable named `errCode` with as value the thrown error's error code. `errorMessageVariable` will allow specifying the variable that will contain the error message.  We will need to document this feature.

#### Additional context
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/24605947/213460249-4b744f3b-5e50-4a52-a75a-b73e81675e6a.png">

Sample XML:
```xml
<bpmn:boundaryEvent attachedToRef="task" id="error-boundary-event" name="error-boundary-event">
    <bpmn:errorEventDefinition errorRef="error_c2c5e107-4c33-4b53-97e8-b09332230a2a" id="errorEventDefinition_11a12a8b-6496-4070-8379-543e1eac52e6">
      <bpmn:extensionElements>
        <zeebe:error errorCodeVariable="errorCode" errorMessageVariable="errorMessage"/>
      </bpmn:extensionElements>
    </bpmn:errorEventDefinition>
</bpmn:boundaryEvent>
<bpmn:error errorCode="ERROR" id="error_c2c5e107-4c33-4b53-97e8-b09332230a2a"/>
```

**Comment by korthout** [comment]
Closed due to:
- https://github.com/camunda/zeebe/issues/12003
