### ISSUE TITLE
Prettier resets indentation level after markdown tables

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-platform-docs#1681]
As described [in this comment](https://github.com/camunda/camunda-platform-docs/pull/1671#discussion_r1095996730), when markdown is indented, and it contains a table, the indentation level gets reset to 0 immediately following the table.

This results in visual misalignment in the docs -- the section below the markdown table doesn't appear to be under the same level of hierarchy.  

This appears to be an issue with prettier, not anything we're doing, but we could still establish a recommendation for how to cope with this. For example, we could decide that ordered list items should be replaced with `####` headings, so that no indentation is required....or we could decide that wrapping the mistakenly out-dented content with `<!-- prettier-ignore-start -->` / `<!-- prettier-ignore-end -->` is the best path.

**Comment by pepopowitz** [comment]
### Notes from a discussion between myself and @christinaausley

Options we could think of: 
1. Convert `1. First thing in the list` to `#### 1. First thing in the list` to convert it to a heading, thus removing the indentation
2. Style ordered lists to not be indented
3. Wrap mistakenly out-dented content with `prettier-ignore` comments.

Things we considered in this discussion:

1. We aren't sure how many pages are like this (an ordered list item, followed by an indented table, followed by an indented paragraph). If it's a lot, we would consider the option to restyle ordered lists globally, but we don't think it's a lot. I (@pepopowitz) will be investigating how many there are.
2. We are wary about the effects on users with touch-up content changes. They don't want to spend a lot of time getting PRs formatted correctly, so we don't want to introduce friction that will slow them down. Options 1 and 3 have potential for introducing this friction, though for most touch-ups, they likely are editing content that doesn't require _introducing_ the proper treatment for indentation.
3. But it's also unlikely that we want indentation removed from ordered lists globally, which introduces a different level of friction as we require people to decide whether their ordered list should be indented or not.
4. More to the point -- the content on the page in question is suspicious. Ordered list items should probably not have long sets of instructions, including tables. This is actually our recommendation -- the page should be written without very-long ordered list items. 
5. Note that this pattern -- ordered list, with an indented table and ensuing paragraph -- does not cause problems when dealing with _unordered_ lists. 🤷 

### Next steps

1. @pepopowitz to find out how many pages are affected by this sequence of elements
2. PRs to rewrite the affected pages (@pepopowitz if it's only a few; otherwise I'll ask for help.)
3. @christinaausley to add guidance on avoiding long instructions within an ordered list item.

**Comment by pepopowitz** [comment]
> @pepopowitz to find out how many pages are affected by this sequence of elements

Good news -- the only two places we have a table indented are [the two files I introduced it to, in the PR that prompted this conversation](https://github.com/camunda/camunda-platform-docs/pull/1671/files) 😅 😬 

So I guess I'll go fix those two places.....

**Comment by akeller** [comment]
FANTASTIC NEWS!

**Comment by christinaausley** [comment]
WE LOVE A QUICK WIN 🥳 Thanks for taking care of this!
