### ISSUE TITLE
Document FEEL expression support for Error throw events

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda-platform-docs#1697]
## Description

With the release of 8.2 we support the error code of a throwing Error event to be a FEEL expression. We should write a sentence or two in [this section](https://docs.camunda.io/docs/components/modeler/bpmn/error-events/#defining-the-error) of the docs that explains this.

**Comment by koevskinikola** [comment]
@remcowesterhoud I just realized that I documented this topic within [this PR](https://github.com/camunda/camunda-platform-docs/pull/1806/files#diff-aa06bacd4fd49c2589f63cf1b923e5c955161a5f00537c183bcfd003d35ee1d0R21-R23).

I'll move this issue to `In Review`. Let me know if you prefer a separate PR for it, or if the existing one is acceptable.
