### ISSUE TITLE
`move-to-done` action fails when a PR hasn't been added to the DX board

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-platform-docs#1707]
## What

We should update the `move-to-done` action so that in the case of no associated DX board item, the workflow succeeds without updating anything.

## Why

The vast majority of PRs have @akeller or @christinaausley added as reviewers. When that happens, the `add-to-project` action adds an item to the DX board for that PR. 

When neither of them are added as reviewers, that action does not add a corresponding item to the DX board. When the `move-to-done` action runs, after the PR is merged, there is no associated project item to look up, and the `move-to-done` action fails with the message `Could not resolve to a node with the global id of ''`.

Example: https://github.com/camunda/camunda-platform-docs/actions/runs/4186555903

**Comment by akeller** [comment]
The irony of this being `closed` but not moved to done.
