### ISSUE TITLE
Add Zeebe Java client configuration example via properties file

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda-platform-docs#174]
Reopened from https://github.com/zeebe-io/zeebe/issues/4763:

**Description**

In the Java client a user can configure the Zeebe client in 2 ways: using the type safe java api or using a `java.util.Properties` object. The latter uses milliseconds as the unit for all durations.

I am unable to find any documentation about this usage, which is why I suggest to introduce an example properties file with the default values for the java client.

This originates from a discussion in #4719

**Comment by akeller** [comment]
@menski can you make a decision here please about documenting this?

**Comment by menski** [comment]
We have the feeling we don't have any configuration options documented for our clients in general, not limited to the properties file.

**Comment by megglos** [comment]
Triaged with @akeller  & @abbasadel :
- we decided to close this one for now, rather follow-up with an overhaul of the client docs

Please reopen if you see a need to tackle this still in isolation.
