### ISSUE TITLE
Make a note about replication factor

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-docs#1743]
I often discovered no in the forum that users are running with an even replication factor, which is problematic.

I recently added a warning to our start-up process https://github.com/camunda/zeebe/pull/11831 but we should also add a note to the docs to make it clearer.

For example, posts where it occurred:

 * https://forum.camunda.io/t/issue-in-connecting-gateway/42841/4
 * https://forum.camunda.io/t/zeebe-startup-issue/36622/4
 * I think there were several on slack

Potential note could be similar as our new warning:

```java
 "Expected to have odd replication factor, but was even ({}). Even replication factor has no benefit over "
          + "the previous odd value and is weaker than next odd. Quorum is calculated as:"
          + " quorum = floor(replication factor / 2) + 1. In this current case the quorum will be"
          + " quorum = {}. If you want to ensure high fault-tolerance and availability,"
          + " make sure to use an odd replication factor.";
```

Or something similar as here https://stackoverflow.com/questions/58823341/why-is-it-recommended-to-create-clusters-with-odd-number-of-nodes

**Comment by akeller** [comment]
@Zelldon do you have a location in mind for this warning in the docs? I think it would be an easy win to add this to the docs.

**Comment by Zelldon** [comment]
@akeller I guess there are multiple places

* https://docs.camunda.io/docs/next/components/zeebe/technical-concepts/partitions/#replication
* https://docs.camunda.io/docs/next/reference/glossary/#replication

**Comment by Zelldon** [comment]
Was also thinking whether it might make sense to add a table like this https://developer.hashicorp.com/consul/docs/architecture/consensus#deployment_table to our docs

**Comment by akeller** [comment]
I like that table, but I **really** like the text immediately before the table with a recommendation and a warning - 

> The recommended deployment is either 3 or 5 servers. A single server deployment is highly discouraged as data loss is inevitable in a failure scenario.

For good Google or searchability, I would also recommend adding the text for your exact warning on [this page](https://docs.camunda.io/docs/next/components/zeebe/technical-concepts/partitions/#replication).

Keep the glossary definition short for replication factor and just add another sentence discouraging even replication factors.

Let's open a PR tomorrow and continue collaboration there 😄 .
