### ISSUE TITLE
Update terminology on Console page

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#1746]
https://docs.camunda.io/docs/apis-clients/console-api-reference/

The Console API Reference docs have some old terminology from the Camunda Cloud days. This doesn't make the terminology I see in camunda.io. 

> To interact with Camunda Platform 8 programmatically without using the Camunda Platform 8 UI, create Cloud API clients in the organization settings under the Cloud Management API tab.

This should be

> To interact with Camunda Platform 8 programmatically without using the Camunda Platform 8 UI, create client credentials in the organization settings under the Console API tab.

All references to Cloud API should be Console API. Cloud API clients should be client credentials. "Cloud API management" still makes sense in context, but if it weren't a title, it would be cloud API management (lowercase cloud).

**Comment by akeller** [comment]
@ultraschuppi can you confirm Cloud API should be Console API and Cloud API clients should be client credentials?

**Comment by ultraschuppi** [comment]
i cannot because it is not my call. i defer to @felix-mueller

**Comment by felix-mueller** [comment]
@akeller Console API makes sense to me. for the second questions I suggest to align with other components, so I am fine with the proposal too

**Comment by akeller** [comment]
This is inconsistent across the product UI, Swagger UI, and the docs.

[Swagger](https://console.cloud.camunda.io/customer-api/openapi/docs/#/) refers to this as "Camunda Management API," which I like more than Console because it's more descriptive, but isn't consistent with the naming anywhere else.

<img width="674" alt="image" src="https://user-images.githubusercontent.com/1051363/223535774-892e40cb-fd4c-419c-9d2f-a516affabc89.png">
 In the product UI, we call this the Console API.
 
In the docs, we call this a mix of Console API and Cloud API management.
 
In the PR, **I'll standardize on Console API** for now because it's the API for the Console component in SaaS. **I'll also standardize on "client credentials."**

If Console is available in the future for SM, we should consider "Camunda Management API" instead.
 
@HanselIdes FYI, since I believe you'd like to be informed of inconsistencies like this.

**Comment by HanselIdes** [comment]
Thanks for the heads-up @akeller . Am I right in assuming there's no further action we need to take in the product?
