### ISSUE TITLE
Rename upgrade to update

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-platform-docs#1765]
We are using the term update for software updates. Upgrade is used for Pricing Plan upgrades.
Therefore e should rename the following section:
https://docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/upgrade/

**Comment by akeller** [comment]
@aabouzaid @christinaausley this looks like something you should both be aware of for this change and moving forward. 

@christinaausley, Felix mentioned one example, but can you search the docs for other examples of **upgrade**? If they exist outside the scope of the Helm Kubernetes docs, please open another issue scoped to tackle those changes.

**Comment by akeller** [comment]
For Helm, the command is actually `upgrade` - https://helm.sh/docs/helm/helm_upgrade/.

@christinaausley in this case, we have a discrepancy for a technical reason. How would you approach this? In the PR, I see you adopted "update" but I'm concerned that's confusing.

**Comment by christinaausley** [comment]
I meant to make an inline comment about this, this is a great conversation.

Currently, I am re-applying `upgrade` to sections which reference specific commands using `upgrade` and aligning with how each company standardizes their terminology and commands.

Collecting external feedback from Write the Docs to finalize this decision and make any final changes in the PR 👍

**Comment by akeller** [comment]
👏 Thank you!

**Comment by christinaausley** [comment]
@felix-mueller Given technically Helm refers to [`upgrade`](https://helm.sh/docs/helm/helm_upgrade/), how do you feel about keeping the original Helm file as `upgrade` and only correcting instances of `upgrade` to software `update` as appropriate in the other files changed in the PR?

**Comment by akeller** [comment]
@christinaausley, Felix is on vacation. Given the other work you are doing, I want to make sure this doesn't block you or create a bunch of merge conflicts.

Please move forward with the approach you mentioned and when Felix is back online he can chime in if he disagrees.
