### ISSUE TITLE
Document Zeebe Elasticsearch exporter

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda-platform-docs#178]
There's very little documentation about the Zeebe Elasticsearch exporter, which is very important internally for our SREs but also for on prem users.

The Operate documentation briefly touches on it, but doesn't describe exactly how to configure it.

We should document:

1. General concept/architecture
2. Configuration
3. How to consume the exported data
4. Pitfalls/known issues

related support case https://jira.camunda.com/browse/SUPPORT-13908

**Comment by upgradingdave** [comment]
Several customers require the ability to connect the Elasticsearch exporter to the elastic cloud, which requires configuring TLS and a custom truststore. Once [this product hub](https://github.com/camunda/product-hub/issues/583) is complete, we should probably also include documentatin about how to configure the elastic search exporter to use tls and a custom keystore.

**Comment by akeller** [comment]
Is this workaround worth documenting now @npepinpe @upgradingdave? I'm not familiar with the Product Gaps repo and how it's triaged.

**Comment by npepinpe** [comment]
I would say yes, since I'm not aware of anyone working on the actual feature, so it may take a while before it's available. The workaround is useful until then for users who are not using certificates signed with common root CAs.

**Comment by upgradingdave** [comment]
Hi @akeller, I agree with @npepinpe, I think it'd be great to document the elastic search exporter now. Maybe we can include a disclaimer that we are still working to add proper support to our helm charts, and show the current workaround?

And, in addition, it might also be a good idea to create a dedicated "How to Configure Elasticsearch Connections" Page somewhere under the Self Managed section of the docs? This new page could then link to the following:  

How to configure Operate to connect to elasticsearch:
https://docs.camunda.io/docs/0.25/components/operate/deployment/configuration/#settings-to-connect

How to configure Tasklist to connect to elasticsearch: 
https://docs.camunda.io/docs/self-managed/tasklist-deployment/tasklist-configuration/#settings-to-connect-to-a-secured-elasticsearch-instance

How to configure Optimize to connect to elasticsearch: 
https://docs.camunda.io/optimize/self-managed/optimize-deployment/configuration/system-configuration/#elasticsearch-security

How to configure Zeebe to connect to elasticsearch:
(could link to this new page describing the elasticsearch exporter)

I found it difficult to find all of these pieces, so I think it'd be good to have this all referenced from one page if possible? What do you think?

**Comment by akeller** [comment]
> I think it'd be great to document the elastic search exporter now. Maybe we can include a disclaimer that we are still working to add proper support to our helm charts, and show the current workaround?

Let's handle this within the scope of this issue (as the workaround, it won't close the issue, but it will serve as a reminder to remove the workaround when the actual feature is done).

@upgradingdave can we partner on a PR? 

Looking at the structure of Self-Managed, where is the best place for this? [Exporters](https://docs.camunda.io/docs/next/self-managed/concepts/exporters/) is in Concepts, which isn't action oriented. What about as a [Guide in Helm/Kubernetes](https://docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/guides/)? We could also pull in @aabouzaid for the best location.

_I moved your other comments into a separate issue specific to a dedicated "How to Configure Elasticsearch Connections" page._

**Comment by upgradingdave** [comment]
Hey @akeller, sure, happy to help with this. 

Maybe we can add a page titled "Elasticsearch Exporter" here? [Self Managed / Zeebe / Operation / Elasticsearch Exporter](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/operations/zeebe-in-production/)
