### ISSUE TITLE
Clarify supported versions of Elasticsearch

### ISSUE THREAD

**Issue by alexcorremans** [camunda/camunda-platform-docs#1808]
The supported versions of Elasticsearch on [this page](https://docs.camunda.io/docs/reference/supported-environments/#camunda-platform-8-self-managed) need to be updated. At the moment it shows 7.16.x, but we've had confirmations internally about some versions of Elasticsearch 7.17. This may need to be checked with the different component teams. 

* [Support ticket](https://jira.camunda.com/browse/SUPPORT-15365) 
* [Slack thread 1](https://camunda.slack.com/archives/C03UR0V2R2M/p1677676320682899)
* [Slack thread 2](https://camunda.slack.com/archives/C03UR0V2R2M/p1678371302974029)

**Comment by alexcorremans** [comment]
Hey @akeller ! This may get a little complicated so it might be best if someone on the Engineering side can coordinate between the different components? How do you usually go about this when there are more teams involved?

**Comment by akeller** [comment]
We have a few options, but the good thing is I sit on the Engineering side 😎 

We have the C8 Stakeholder meeting or the ELT meeting, both of which I attend, and I can bring this up as a topic. I'll go ahead and assign myself this topic to move things forward.

**Comment by alexcorremans** [comment]
Awesome, thank you @akeller 😎 !

**Comment by akeller** [comment]
* Operate/Tasklist - https://camunda.slack.com/archives/C9B5270DA/p1679498734542399
* Zeebe Broker and Gateway - https://camunda.slack.com/archives/CSQ2E3BT4/p1679498693209949
