### ISSUE TITLE
Document Opensearch Exporter

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda-platform-docs#1828]
We should With 8.2 Zeebe officially supports an Opensearch Exporter. This is already pretty well documented in the [README of this exporter in Zeebe](https://github.com/camunda/zeebe/tree/main/exporters/opensearch-exporter#zeebe-opensearch-exporter).

We should also add this documentation to the official docs. For users this is easier to find. It also provides clearer versioning, which we don't have in the README.

Besides this in the [Supported Environments](https://docs.camunda.io/docs/reference/supported-environments/) part of the docs we mention that there is no support for Opensearch. This must be removed.

Note: there is also an [open issue](https://github.com/camunda/camunda-platform-docs/issues/178) to document the Elasticsearch Exporter

**Comment by remcowesterhoud** [comment]
@akeller I'm struggling to find a good place where to document our exporters. I believe it should be part of the self managed docs, as SAAS users don't have to worry about exporting.

We have an [Exporters section](https://docs.camunda.io/docs/self-managed/concepts/exporters/) in the concepts part of the self managed docs. However, this is more generic information on how exporters work and not about specific Exporters that we provide as Camunda.

We also have a [small part](https://docs.camunda.io/docs/self-managed/operate-deployment/operate-configuration/#zeebe-elasticsearch-exporter) in the Operate section of the self managed docs, but this is more about how to connect Operate to Elasticsearch.

I think we need a new `Exporters` section. We can either put it under `Zeebe` or as a top-level page. What do you think is best?

**Comment by akeller** [comment]
Great question, thanks for tagging me ❤️ 

My preference would be to put this under Zeebe, but with the Zeebe Gateway also at the top-level, you could argue either place would work. (TBH, we should move the Zeebe Gateway doc, but that's out of scope for this issue.)

Do you see documenting more Exporters in the near future? It would be good to have a general or overview page on exporters and then individual pages for each specific exporter.

My recommendation - Create a new section for Exporters under Zeebe (Self-Managed), but link to the existing content on exporters for the most comprehensive experience in an overview page.
