### ISSUE TITLE
Update the FEEL docs for version 1.16

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-platform-docs#1846]
## Description 

Zeebe 8.2 will include the latest version of the FEEL engine [1.16](https://camunda.github.io/feel-scala/docs/changelog/).

Following the established process, we need to copy to [FEEL docs](https://camunda.github.io/feel-scala/docs/reference/language-guide/language-guide-introduction) into this repository. 

Instead of updating only the last version, we should also update previous versions to add the `Camunda Extension` marker for the built-in functions. This was requested by the modeling team.

**Comment by akeller** [comment]
@saig0 should we expect a PR on Tuesday morning with these updates?

**Comment by saig0** [comment]
@akeller I plan to work on it today. 

If you want to release the documentation version before, it's okay. I can backport the changes to version `8.2`.
