### ISSUE TITLE
0.26 links are removed from index, yet still reachable

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#1905]
https://docs.camunda.io/docs/0.26/reference/bpmn-workflows/multi-instance/ continues to come up as a popular URL for Google Search Console. It's canonical, yet should not be indexed since it's an older version of the docs.

The content was moved to a new home (from Reference to Components > Modeler) which may be part of the reason its continuing to come up. 

I view this as a bug, but something that can wait until after the upcoming release.

**Comment by pepopowitz** [comment]
My suspicion is that to correct this specific page, we will have to do all the things recommended in #1143, in which case it will be done for _all_ older version pages. I'm not sure what to do with this suspicion, but I wanted to state it.

**Comment by akeller** [comment]
As the DRI of this domain, feel free to close it and consolidate.

**Comment by pepopowitz** [comment]
Closing this as I think it will be resolved by #1143
