### ISSUE TITLE
Replace `linkcheck` tool in scheduled link checking

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-platform-docs#1964]
Our scheduled link checking fails more often than not, with connection failures. This is a tendency we also noticed in our PR builds, and appears to be inherent in the `linkcheck` tool we are using in our [`Check Links`](https://github.com/camunda/camunda-platform-docs/blob/main/.github/workflows/linkcheck.yaml) workflow.

We should look at alternatives to crawl and link-check the staging and production sites *on a scheduled basis*. 

## Implementation considerations

- look at https://github.com/camunda/camunda-platform-docs/pull/1941 for alternatives.
   - Though keep in mind that tools that check source files won't work for this workflow, as we want to check the served pages on the staging/production sites.

**Comment by pepopowitz** [comment]
@pepopowitz wants to look at the workflow runs more closely to see if we are getting _any_ signal from noise in this action, which is 100% failing right now.

**Comment by akeller** [comment]
I would vote to remove this action.

**Comment by pepopowitz** [comment]
+1, I gave up paging backward in time to find the last time this workflow succeeded. 

PR incoming.
