### ISSUE TITLE
Zeebe Gateway Interceptor is not in sidebar

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-platform-docs#1987]
The Zeebe Gateway Interceptor page is not part of the sidebar:
<img width="1646" alt="Screenshot 2023-04-19 at 10 45 58" src="https://user-images.githubusercontent.com/3511026/233020687-4b2e23ea-94de-49d0-979e-fdd04f072f36.png">

The page is accessible via `Zeebe Gateway > Overview > Interceptor Configuration`
<img width="1647" alt="Screenshot 2023-04-19 at 10 45 26" src="https://user-images.githubusercontent.com/3511026/233020534-697eccc4-d42f-4136-b4eb-ffce3202423e.png">

**Comment by akeller** [comment]
@korthout do you need any support or assistance from DevEx?

**Comment by akeller** [comment]
I'll add it to our board and see who gets to it first.

**Comment by korthout** [comment]
ZPA triage: 
- We'd also like to move Zeebe Gateway inside the Zeebe category in the sidebar (confusing that it's separate (and so much lower), @akeller what do you think?)

**Comment by akeller** [comment]
100% agree

**Comment by akeller** [comment]
Zeebe Gateway was already moved inside the Zeebe category, but I took care of the rest of the open items here in my PR 😎
