### ISSUE TITLE
Improve webhook connector documentation

### ISSUE THREAD

**Issue by chillleader** [camunda/camunda-platform-docs#1999]
We should address the [customer feedback](https://camunda-platform.slack.com/archives/C0497FR8XML/p1681894001880569) related to the webhook connector documentation.
- Clearly mention that webhook currently only supports GET request
- Elaborate why Operate is a required dependency for inbound Connectors and what limitations this dependency causes

**Comment by upgradingdave** [comment]
Hi Team, the documentation page for our [inbound webhook connector](https://docs.camunda.io/docs/components/connectors/out-of-the-box-connectors/http-webhook/) has this line:

```
2. (Optional) Configure HMAC authentication if required. Not recommended: leave it disabled to ignore HMAC verification if your use case doesn't require verification or your use case is not yet supported.
```

This was misinterpreted recently to mean that HMAC shouldn't be used, when it actually means the opposite! 

So, perhaps reword that line to use simpler language? Maybe even just shorten it to be:

```
2. Optionally Configure HMAC authentication if required.
```

Thanks!

**Comment by akeller** [comment]
Addressing the comment above, I would recommend rewording the “not recommended” statement to either something affirmative and/or into a Docusaurus admonition.
