### ISSUE TITLE
Document date time support in intermediate, boundary and event subprocess timer events

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda-platform-docs#2012]
## Description
Zeebe now supports date time in intermediate, boundary and event subprocess timer events. This is not reflected [in the documentation](https://docs.camunda.io/docs/8.1/components/modeler/bpmn/timer-events/).

We should mention the support for date times. We should also explain the behavior for boundary and event subprocesses. Once the date time is reached the timer is triggered. The timer can only trigger once at the specified date time.

**Comment by aleksander-dytko** [comment]
@remcowesterhoud as [Modeler](https://github.com/camunda/camunda-modeler/issues/3516) will release it soon, I'll add this as the priority for the next iteration.
