### ISSUE TITLE
No link to Connector SDK

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#2034]
https://docs.camunda.io/docs/components/connectors/custom-built-connectors/connector-sdk/ doesn't include a link to the actually Connector SDK repo. Is this intentional? 

It should link to https://github.com/camunda/connector-sdk.

**Comment by igpetrov** [comment]
I guess, it was intentional because the repository was different back those days. Right now we have a concrete repository link. I will take care and update this.
