### ISSUE TITLE
Connector SDK page only references Outbound Connectors

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#2045]
Connector SDK page only references Outbound Connectors, but the [Connector SDK README](https://github.com/camunda/connector-sdk#readme) suggests you can build custom Inbound Connectors with it too.

* Add documentation for Inbound Connectors or clarify that Outbound Connector code snippets were used as examples.
* Reference template repositories in the docs directly (currently only available on the SDK README).
* Link from the Connector SDK README to the Connector SDK docs page.

**Comment by igpetrov** [comment]
Hi @akeller

> Add documentation for Inbound Connectors or clarify that Outbound Connector code snippets were used as examples.

Added it in the [PR](https://github.com/camunda/camunda-platform-docs/pull/2055): [here](https://github.com/camunda/camunda-platform-docs/blame/a62f6d0a19e6332c24cfbc8ea3dcf5e8a3cf3b81/docs/components/connectors/custom-built-connectors/connector-sdk.md#L38-L42) and [here](https://github.com/camunda/camunda-platform-docs/blame/a62f6d0a19e6332c24cfbc8ea3dcf5e8a3cf3b81/docs/components/connectors/custom-built-connectors/connector-sdk.md#L359)

> Reference template repositories in the docs directly (currently only available on the SDK README).

[Done](https://github.com/camunda/camunda-platform-docs/pull/2055) 

> Link from the Connector SDK README to the Connector SDK docs page.

[Done](https://github.com/camunda/connector-sdk/blame/main/README.md#L9)

Please let me know if I missed anything
