### ISSUE TITLE
Evaluate & restructure community clients content

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#2048]
Most of our community clients are specific to Zeebe, but we have other components like Tasklist represented as well. 

We have community-supported clients for all components in NodeJS, along with a NodeJS Connector SDK. 

Community-supported content in the APIs & Tools space helps our polyglot story or mission.

We could consider the following:

***Add all community-supported clients, including non-Zeebe ones*** Resolved in https://github.com/camunda/camunda-platform-docs/issues/2068.
* Consolidate community-supported projects (clients & SDKs) to a single page with tabs 
* Evaluate whether stale clients or clients with no maintainer should be linked on the docs
* Structure pages so page clicks/views help us collect information on interest in particular programming languages.

**Comment by akeller** [comment]
Might be an interesting one for you @christinaausley! Feel free to add yourself as an assignee and move it into the `Backlog`. If you aren't interested, ignore this :)

**Comment by christinaausley** [comment]
This can be closed out IMO. Based on the work you've been doing to plan out API strategy, we can always build a new issue to prioritize fixes.
