### ISSUE TITLE
Running docs locally results in core dumps

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#2049]
This was raised internally and the first time I've heard about it. I cannot reproduce this, but I'll admit I also didn't try too hard.

> Running our [documentation](https://github.com/camunda/camunda-platform-docs) locally I experience some operational issues: The application simply core dumps on both node@16 and node@18, apparently with an out of memory error.

Crashes after initial build worked during npm start
node v16.18.0 (npm v8.19.2)

Internal Slack - https://camunda.slack.com/archives/C026U8GBNSW/p1682587183288679

**Comment by akeller** [comment]
@pepopowitz Nico indicated this wasn't urgent, so before digging, check the Slack thread or see if there is any new/different chatter about this. 

Given Christina and I are in the docs daily and running/building multiple times and haven't hit any issues, it's possible it could be something with Nico's setup.

**Comment by nikku** [comment]
@akeller @pepopowitz I'll close this issue. A clean cache, checkout + re-install and things _seem_ to work stable again.

**Comment by marstamm** [comment]
I ran into the same issue today. I resolved it by increasing the maximum node Heap size:

```sh
export NODE_OPTIONS=--max-old-space-size=10248
npm run start
```
