### ISSUE TITLE
Remove orphaned "Tasklist API" page for Self-Managed

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-platform-docs#2056]
There is an orphaned and outdated page for the Tasklist API that should be removed: https://docs.camunda.io/docs/next/self-managed/tasklist-deployment/tasklist-api/#self-managed-api

Ingoing links should be redirected to the new Tasklist API pages.

**Comment by akeller** [comment]
@christinaausley can you assist here? This looks like an easy pick for us.

**Comment by christinaausley** [comment]
On it!

**Comment by christinaausley** [comment]
@christian-konrad Does **only** the section referring to #self-managed-api need to be removed here, or is there additional content you want to keep in this page or adapt into the existing Tasklist API pages?

**Comment by christian-konrad** [comment]
@christinaausley good catch! I accidently shared the anchor link. The full page can be deleted, the whole content is either duplicate or outdated.

Thanks!
