### ISSUE TITLE
Add non-Zeebe Community Clients to docs

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#2068]
In APIs & Tools, we list our Zeebe clients, but we have a few non-Zeebe clients maintained by our community that should also be included for better visibility. 

Increasing the visibility will help us determine if we should move to support these projects fully.

The following clients should be linked as community-supported clients:

* https://github.com/camunda-community-hub/console-client-node-js
* https://github.com/camunda-community-hub/operate-client-node-js
* https://github.com/camunda-community-hub/camunda-operate-client-java
* https://github.com/camunda-community-hub/dotnet-custom-tasklist
* https://github.com/camunda-community-hub/camunda-tasklist-client-java
* https://github.com/camunda-community-hub/tasklist-client-node-js
* https://github.com/camunda-community-hub/optimize-client-node-js

**Comment by akeller** [comment]
@christinaausley @jwulf @pepopowitz I've added you as reviewers to this PR, but I realize I should have brought you into a discussion on this issue first.

I intend to highlight more community projects to help gauge interest in specific programming languages to inform our client and SDK work. Does this make sense to you? Or does it feel counter to our approach to only documenting fully supported things? Any additional feedback?

**Comment by christinaausley** [comment]
@akeller I think this is an excellent idea to gauge interest. We can always revisit and prune as necessary.

**Comment by akeller** [comment]
@xomiamoore @mary-grace, any thoughts on this issue or the PR? Currently, our documentation only links to the Zeebe community clients, which is a partial picture of the community clients we have today.

**Comment by pepopowitz** [comment]
> @christinaausley @jwulf @pepopowitz I've added you as reviewers to this PR, but I realize I should have brought you into a discussion on this issue first.
> 
> I intend to highlight more community projects to help gauge interest in specific programming languages to inform our client and SDK work. Does this make sense to you? Or does it feel counter to our approach to only documenting fully supported things? Any additional feedback?

I think this is great! As a community member I'd be excited to find out my project got added to Camunda's (unsupported) list of community projects.

**Comment by xomiamoore** [comment]
I think this is a great idea, as long as it's very clear which are community clients and which are official!

I think we should add something to the Community Hub documentation on how to submit a PR to include any future client libraries to the C8 docs. 🤔 I can add that to my list.

**Comment by akeller** [comment]
In the PR I added the changes to 8.2, but don't plan on backporting further than that.
