### ISSUE TITLE
Remove Cawemo references from docs

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-platform-docs#2138]
Since we are about to sunset Cawemo (c.f. https://docs.google.com/document/d/1EsDyWMJenJkKLqdZ9bEjTD9-BDRrRrE-23QrgP1xjm0/edit#), and will soon stop new signups (c.f. https://github.com/camunda/cawemo/pull/11180), we want to remove references to Cawemo from the docs, in order to avoid confusion and misleading "advertising", and to keep the docs lean.

Pages to update:

- https://docs.camunda.io/docs/components/best-practices/architecture/deciding-about-your-stack-c7/
- https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/element-templates/additional-resources/
- https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/element-templates/configuring-templates/#example-windows

**Comment by akeller** [comment]
You read my mind! I was just thinking about Cawemo content today.

I'm interested in reviewing all the Guides content, which includes https://docs.camunda.io/docs/guides/migrating-from-cawemo/

Should we set an EOL date for this instead?

**Comment by christian-konrad** [comment]
@akeller Sure! We could offer some helpful guidance here for migration. I am also preparing an internal doc that outlines how you can use those diagrams in Web Modeler to implement them for C7 using Desktop Modeler, however we first want to understand if this is not mixing up too many things and promoting wrong usage of our products. Happy to hear your thoughts here
