### ISSUE TITLE
Misleading documentation on Incidents for unexpected exceptions

### ISSUE THREAD

**Issue by jothikiruthika** [camunda/camunda-platform-docs#2211]
[Documentation on incidents](https://docs.camunda.io/docs/components/concepts/incidents/) states that "Incidents are not created when an unexpected exception (e.g. NullPointerException, OutOfMemoyError etc.) occurs."

When there is a nullPointerException thrown in the worker, an incident does get created. This information is misleading. If this is documented from zeebe's perspective, where a process instance gets blacklisted and doesn't show up in Operate, then this has to be clarified in the documentation, else it is confusing the users.

**Comment by akeller** [comment]
Conversation on ask-documentation - https://camunda.slack.com/archives/C026U8GBNSW/p1686558833353119

**Comment by akeller** [comment]
> Incidents are created explicitly by job workers sending FAIL commands or implicitly when a job is out of retries, input/output-mapping can't be applied or a condition or decision can't be evaluated. Note that not all errors will necessarily lead to incidents. For example, unexpected errors in Zeebe do not always result in incidents.

I will PR with something similar to the above quote.
