### ISSUE TITLE
OAuth URL unclear for Desktop Modeler to C8 SM

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#2237]
To connect from Desktop Modeler to C8-SM with OAuth, the OAuth URL needs to be:
https://<keycloakServerFQDN>/auth/realms/camunda-platform/protocol/openid-connect/token
But this isn't very easy to figure out.

https://camunda.slack.com/archives/C026U8GBNSW/p1686678137594199

**Comment by barmac** [comment]
I see that oauth is now available out of the box: https://docs.camunda.io/docs/self-managed/zeebe-deployment/security/client-authorization/#camunda-identity-authorization
Yet, in the Desktop Modeler docs we still point out to a community project: https://docs.camunda.io/docs/self-managed/modeler/desktop-modeler/deploy-to-self-managed/

I haven't tried the out of the box solution yet, but for sure the Modeler docs should direct user to the identity authorization page for details.

**Comment by akeller** [comment]
@barmac is this something you could add to your team board, test out, and then make the relevant fixes?

Adding the URL is relatively easy (once confirmed), but the URL in the screenshot looks like it points to SaaS. Should that be changed too?

**Comment by barmac** [comment]
I will create an issue for this on our team board, but we are not likely to look into this until after the retreat.

**Comment by barmac** [comment]
Follow-up: https://github.com/bpmn-io/internal-docs/issues/781

**Comment by nikku** [comment]
@akeller I suggest that we update the screenshot once we rework _all_ of the shots. They all still feature modeler v5.8 / Camunda 8.0 (Zeebe 1.3) and are worth refreshing at some point.
