### ISSUE TITLE
Document the `camunda-zeebe-identity-secret`

### ISSUE THREAD

**Issue by upgradingdave** [camunda/camunda-platform-docs#2291]
A new feature was added in 8.2 to enable oauth2 security to the zeebe gateway. 

The following pages should be updated to include a mention of `camunda-zeebe-identity-secret`

* [Upgrade Steps for 8.2](https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/upgrade/#v82)
  * #2157
  * #2234
* [Secrets Extraction](https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/upgrade/#secrets-extraction)
  * #2355

**Comment by aabouzaid** [comment]
Closing this issue since all PRs have been merged.
