### ISSUE TITLE
`react-components/iso-8601-date-time` is searchable via cmd+k

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-platform-docs#2320]
I was looking for documentation on timers, so I used search feature and landed on this page: https://docs.camunda.io/docs/next/components/modeler/bpmn/assets/react-components/iso-8601-date-time/

![image](https://github.com/camunda/camunda-platform-docs/assets/28307541/9072a188-3ec4-40a8-a1dd-2def3e8eb5eb)

It doesn't look like a valid documentation page.

Found via search:

![image](https://github.com/camunda/camunda-platform-docs/assets/28307541/345716a0-f28c-4bae-b07e-b859260c10e2)

I believe the page should not be accessible to users, and should not be searchable.

**Comment by akeller** [comment]
This change is live, but I'm going to manually trigger the Algolia crawler (since it runs every Tuesday). This should allow us to test exactly the behavior happening here and confirm this is fixed 🤞

**Comment by akeller** [comment]
This is **not** showing up in the results for me for any supported version 🎉
