### ISSUE TITLE
Docs don't explain the hybrid setup of Connectors

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-platform-docs#2351]
### Problem description

A customer highlighted that they were not aware of the possibility to set-up Connectors (which are really just job workers) in a hybrid set-up: Camunda 8 Platform running in SaaS, Connectors running on-premise.

The core problem they solve with this (which could be highlighted in the docs) is: accessing enterprise resources that exists behind the company firewall.

Because it was not clear to them, they over-complicated their implementation solution design and lost time.

### Improvement proposal

We should evaluate where / how we explain the hybrid set-up.

Potentially it makes sense to have a guide on this, since it spans across components.

### Context

https://jira.camunda.com/browse/SUPPORT-17540

**Comment by igpetrov** [comment]
Working on it at https://github.com/camunda/camunda-platform-docs/pull/2510

**Comment by igpetrov** [comment]
Docs PR has been merged. Closing.
