### ISSUE TITLE
[Bug] Include use-case for Slack "slash" commands

### ISSUE THREAD

**Issue by igpetrov** [camunda/camunda-platform-docs#2353]
As per [user request](https://camunda.slack.com/archives/C02UMKN3DTL/p1689861511192799?thread_ts=1689756653.963699&cid=C02UMKN3DTL), it turned out that documentation is not obvious how to extract data from Slack slash-command request.

The goal of this task is to include a relevant example to the ticket.

**Comment by quentinleroy** [comment]
The Camunda documentation shows the following example screenshot with "Activation" and "Result Expression" fields hinting at using `request.body.event.XXX` as the variable to use to parse parameters from the Slack POST request.  
<img width="960" alt="Screenshot 2023-07-20 at 18 13 49" src="https://github.com/camunda/camunda-platform-docs/assets/24291958/07a974fc-be97-49c9-abf7-1cfaf49074a1">
In reality, the following variable is needed: `request.connectorData.XXX` and can be used to activate and parse parameters in result expression.

**Comment by igpetrov** [comment]
@quentinleroy the `request.body.event.XXX` is still valid though for event API but not slash-commands.
