### ISSUE TITLE
Add a section around Usage Metrics and their definition

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-platform-docs#2391]
We will need a definition of our usage metrics and their definition.
In C7 docs we have something similar like: https://docs.camunda.org/manual/7.19/user-guide/process-engine/metrics/

From this page we should then link to SaaS and SM ways of finding out about the metrics, e.g. Billing Page in Console vs. currently API way in SM.

**Comment by akeller** [comment]
Do you need any help with this? It may be easiest for you to draft something, and then after reading what you draft, I can help you find a good place for it in the docs.

**Comment by akeller** [comment]
https://docs.google.com/document/d/1Fre_Nb51NfwiKyBmv0Ue9sOuJH0eMAcB3ZhVq-DjqkQ/edit

**Comment by felix-mueller** [comment]
Thanks for adding the doc!

**Comment by akeller** [comment]
@felix-mueller do you have a timeline or date for when you want this page added? I see there are some questions and review requests in the doc.

**Comment by felix-mueller** [comment]
@akeller review from stakeholders in document is done, CSM is fine and Engineering added details for Operate, Tasklist.
I believe we can go next steps now to bring it into docs.
ideally I would like to get this done as soon as someone on your team has bandwidth for it :) no concrete deadline.

**Comment by akeller** [comment]
@jprcoliveira FYI I saw you have some usage alert work going on. This PR added a new page for usage metrics (not live in production, so here is a stage link - https://stage.docs.camunda.io/docs/8.1/reference/usage-metrics/). It would be good to update (or link!) this page with when or how alerts are triggered.

**Comment by jprcoliveira** [comment]
> @jprcoliveira FYI I saw you have some usage alert work going on. This PR added a new page for usage metrics (not live in production, so here is a stage link - https://stage.docs.camunda.io/docs/8.1/reference/usage-metrics/). It would be good to update (or link!) this page with when or how alerts are triggered.

thank you @akeller for the heads up. I will add this to my to-do list for next week.
