### ISSUE TITLE
Remove "API endpoints", use "API orchestration"

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#2444]
API endpoints and API orchestration are used interchangeably in the context of Connectors, and it's difficult to understand if they are related or even the same. 

API orchestration has a better chance of resonating with our users. 

This change should be communicated internally via #ask-documentation and reiterated in onboarding and Academy channels.

https://camunda.slack.com/archives/C02JLRNQQ05/p1692126405979069?thread_ts=1684177781.748689&cid=C02JLRNQQ05

**Comment by christinaausley** [comment]
Ooooooh this sounds up my alley. Let me know if I can assist here 👍
