### ISSUE TITLE
Improve "Orchestrating human tasks" guide

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-platform-docs#2450]
The guide for human task orchestration is one of the most popular docs. However, it is out-of-date, and lacks describing key concepts that are relevant for success like

* I/O mapping for the user task
* Using the "key" property to map to a process variable
* Using the mock data panels to test a form and define output
* Updating a form
* Use results from a form to drive process decisions
* Use Tasklist properly

We should also link then in the "Read more" section to
* Start forms doc
* Start process from Tasklist doc

<img width="1629" alt="image" src="https://github.com/camunda/camunda-platform-docs/assets/56470362/bd6efaa4-816b-43de-b9d1-4de632d28b42">

We should update the page and track it's impact on user success and activation continously (see [report](https://eu.mixpanel.com/project/2665743/view/3203023/app/boards#id=5455667)).

**Goal**: users who read the guide should be significantly more successful (e.g. more deployments of HTO processes compared to non-readers). At the moment, they are only slightly more successful

<img width="1951" alt="image" src="https://github.com/camunda/camunda-platform-docs/assets/56470362/f2ccda9c-cd5e-4c16-baae-10e692c84ba2">

**Comment by akeller** [comment]
Since this is part of the **Getting started guides**, changes and their impact have been part of the Onboarding team experiments. We only have bandwidth to review and monitor SEO concerns more holistically, so we don't have a validation or success metric per page.
