### ISSUE TITLE
Remove Search from unsupported versions

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-platform-docs#2475]
Part of #1173.

The Search results in unsupported versions are unhelpful. They are generated based on the main docs site (docs.camunda.io), which uses a different URL schema for versioning than the unsupported sites. As a result, the version number appears twice in each search result URL. 

## Example

Searching for "BPMN primer" on https://unsupported.docs.camunda.io/1.2/ gives the following top result: https://unsupported.docs.camunda.io/1.2/docs/1.2/reference/bpmn-processes/bpmn-primer/. 

That URL does not exist. On the main site, the URL would be docs/1.2/reference/bpmn-processes/bpmn-primer/....on the unsupported site, the URL would be 1.2/docs/reference/bpmn-processes/bpmn-primer/. Instead, we get a hybrid that leads to a 404.

## Proposal

Since these docs are for *unsupported* versions only, we should remove the Search entirely. It's not helping anyone, and it is non-trivial to fix.

```[tasklist]
## Progress
- [ ] #2542 
- [ ] #2545
- [ ] #2546
- [ ] #2547 
- [ ] #2548
- [ ] #2549
- [ ] #2550 
``` 

## Alternatives

1. Figure out how to make the search results in the correct versioned format.

There is probably a way to swizzle the Search components and remove the duplicate version number from the target URL.

The down-sides to this approach are:

* This would take the most effort out of all suggestions discussed.
* There would still be a chance that a URL was incorrect -- if the target doc's URL did not match in production vs the unsupported version (e.g. it was moved). 

3. Add redirect rules to an unsupported site's htaccess.

One rewrite rule would cover everything -- it would look for the duplicate version number, and rewrite the URL without it. 

The down-side of this approach is:

* There would still be a chance that a URL was incorrect -- if the target doc's URL did not match in production vs the unsupported version (e.g. it was moved).

**Comment by akeller** [comment]
Given the relatively low use of search (historically and currently, compared to page view traffic), your proposal makes a lot of sense to me. Let's not invest time in fixing this for each site.
