### ISSUE TITLE
Move CI/CD guide to next steps + copy to 8.2

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-platform-docs#2497]
We should move the CI/CD guide to "next steps" to comply with the current structure, and copy it to 8.2 since thats the default docs version users see. 

Even while the guide uses some 8.3 features, we need to increase awareness for the guide; and the main feature (the API) is available in 8.2.

**Comment by akeller** [comment]
@christian-konrad for good board hygiene, don't forget to move this to Done on the Modeling Group board (I cannot do it for you).
