### ISSUE TITLE
Names of AWS & Amazon Connectors are not interchangeable

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#2567]
I noticed in our AWS section of the Connectors docs we flip between AWS and Amazon depending on the technology. I contacted some folks I know at Amazon who informed me these are **not interchangeable**. 

**Each service has a prefix, and it’s unique to the service.**

- ❌ AWS DynamoDB Connector —> Amazon DynamoDB Connector
- Amazon EventBridge Connector —> Correct as written here
- ❌ AWS EventBridge Webhook Connector —> Amazon EventBridge Webhook Connector
- AWS Lambda Connector —> Correct as written here
- Amazon SNS Connector —> Correct as written here
- Amazon SNS inbound Connector —> Correct as written here
- Amazon SQS Connector —> Correct as written here
- Amazon SQS inbound Connector —> Correct as written here

When in doubt, search for an Amazon product page to confirm AWS vs. Amazon.

Changes should be made to the sidebars and docs pages for all supported versions (8.0+). 

We should also document this internally so we are aligned across all externally facing assets to respect proper branding and brand names.

**Comment by christinaausley** [comment]
See https://confluence.camunda.com/display/HAN/Product+Glossary for the ongoing glossary. A PR is in the works!

**Comment by christinaausley** [comment]
Going to cap this issue at Amazon references -- will create a backlog issue for the remaining terminology, like macOS.
