### ISSUE TITLE
set up a formatter for the markdown

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-platform-docs#299]
## Progress

- [x] #815 
- [x] #833 
- [x] #874 
- [x] #876
- [x] #883

## Background

In reviewing code it makes sense to have a automated formatter to end discussions about styling. The same goes for Markdown files.

I know that prettier has [markdown support](https://prettier.io/blog/2017/11/07/1.8.0.html#markdown-support), which also does line wrapping for text through [prose-wrap](https://prettier.io/docs/en/options.html#prose-wrap) and is a node package so should work with the development environment of this repo. 

Personally, I'm no fan of the line wrapping at fixed line length for Markdown, but at least it would add consistency to Markdown styling.

_Originally posted by @korthout in https://github.com/camunda-cloud/camunda-cloud-documentation/pull/298#discussion_r659823177_

**Comment by korthout** [comment]
@akeller How do you feel about this?

**Comment by akeller** [comment]
I do not write with line wrapping in mind, code or sentences, so it makes sense that we should look to have an automated formatter. That said, I don't have any strong opinions on this, but I have used Prettier before and have no objections to it. Plus I want to be part of a [hype train](https://prettier.io/docs/en/why-prettier.html#ride-the-hype-train) and I see they have an extension on VS Code. 👍 
 
I do know it is a very controversial topic, [for example](https://prettier.io/docs/en/why-prettier.html#ride-the-hype-train). In the [Google Technical Writing Style guide](https://developers.google.com/style/html-formatting#line-length) that we are looking to use as our backbone today, they suggest 80 characters, with notable exceptions like links. 100 vs. 80 doesn't matter to me, but I agree let's standardize.

@christinaausley do you have any thoughts here? I don't think we considered this for the style guide draft (yet).

**Comment by korthout** [comment]
IMHO, I think that char length wrapping of readable text is not **as** useful as with "normal" code. Editors and visualizers are generally capable to do soft wrapping of the lines. And most editors (like VSCode) even offer rendered Markdown previews.

Instead, in my ideal world, Markdown would be wrapped after each entire sentence. This would help version control in better showing changes.

Consider the following in which I'd replace the word three for four.
```
In this great example, we start with a short sentence. Then we follow it with another three
sentences. But they are all hard wrapped at 100 chars. So, when I change the word three to four
then it would not be clear in the diff what I'm actually talking about. Three x became four x, but
x is not known, because it exists on a line that did not have to change.
```
```
-In this great example, we start with a short sentence. Then we follow it with another three
+In this great example, we start with a short sentence. Then we follow it with another four
```
I'd rather have:
```
-Then we follow it with another three sentences.
+Then we follow it with another four sentences.
```

Another example, is that everything changes when we take one of the sentences and remove a few words or add a few words. 
Luckily, GitHub can highlight the words that changed. But, hard char limit line wrapping make it hard to provide suggestions in a review.

Sadly, I don't think any of the formatters support this type of line wrapping. I just wanted to offer my 2 cents on better practice. In the end, I'd rather have consistency. So my preference goes to some hard check in the CI pipeline that I can also apply locally. Prettier has both a check and a format command which makes it great in my opinion.

**Comment by akeller** [comment]
@pepopowitz this is definitely up your alley and sounds like something you were already thinking about exploring. Again, not sure its a "good first-timers" issue, but it's relatively small.

**Comment by korthout** [comment]
Hi @akeller and @pepopowitz, I actually spent some spare time last weekend on this topic: adding prettier in a way that we can enable it in steps to the files, instead of all in one go. Feel free to have a look here and use what you find is useful.

Sorry that I didn't make it clear that I had already spent some time on it 🙇
