### ISSUE TITLE
Documenting Gateways in CCaaS

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#380]
After a discussion with @korthout we realized we might need more documentation on gateways in CCaaS ([CCSM too, but that's a separate issue](https://github.com/camunda/camunda-platform-docs/issues/381)).

How do Gateways work in CCaaS?
* No stand alone, embedded, broker with a gateway, always running on the same machine
* Many gateways and many brokers depending on cluster plan
* SRE topics
    * What about stand alone gateways? 
    * Are we providing multiple gateways for dev clusters?

To do:

- [ ] Update [architecture diagram](https://docs.camunda.io/docs/product-manuals/zeebe/technical-concepts/architecture) (currently implies 2 gateways, decoupled from brokers) or clarify what a dev cluster looks like
- [ ] Update [gateway](https://docs.camunda.io/docs/product-manuals/zeebe/technical-concepts/architecture#gateway) documentation for CCaaS
- [ ] Update [glossary definition](https://docs.camunda.io/docs/reference/glossary#gateway) if needed

Are we missing anything from the CCaaS perspective?

**Comment by megglos** [comment]
@akeller I'm tempted to argue this can be closed, I don't think we need to document the details on how clusters are setup for SaaS, as this also can change anytime and may vary depending on the clusterplan. wdyt? @akeller @korthout ?

**Comment by korthout** [comment]
My point was that Zeebe's technical concepts only has the following to say about gateways: https://docs.camunda.io/docs/next/components/zeebe/technical-concepts/architecture/#gateways

This while it goes into a lot of detail about clustering and partitioning. 

I think it makes sense to add more detail about gateways in the zeebe technical concepts.

**Comment by megglos** [comment]
Basically some more details as documented [in the Self-Managed Zeebe docs](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/zeebe-gateway/overview/) but with less detail?

I'm in favor on improving the docs of explaining what the gateway component is, I just lack a clear understanding what the scope should be. From the arguably brief content on the page linked I could imagine to add the following:
- gateway routes client requests to brokers within the cluster - client doesn't need to deal with that complexity
- to do that the gateway is partition aware and communicates with the current leader of a particular partition
actually very close to what is documented here https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/zeebe-gateway/overview/#why-do-we-have-the-zeebe-gateway-and-what-problems-does-it-solve

the objective being: **give the user an understanding of the purpose and function of the gateway**

I wouldn't go into further detail like how the gateway can be run (standalone vs embedded) neither how it's setup in SaaS (As this is subject to change, may differ by cluster plan and actually not relevant for the user? If we want to document that it may rather be in a section of the docs that makes details of cluster plans transparent on which SRE might be the best point of contact)

**Comment by megglos** [comment]
Triage with @akeller:
- we will close this for now as we don't see a strong need for a SaaS user to understand the Cluster setup more deeply
