### ISSUE TITLE
Add BPMN/DMN Model API docs

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#447]
The BPMN Model API is available with Zeebe properties for Camunda Cloud - https://github.com/camunda-cloud/zeebe/tree/develop/bpmn-model

But not documentation exists. We are looking at using the existing Platform documentation and modifying it for Cloud, while specifying it is not a public AP - https://docs.camunda.org/manual/7.16/user-guide/model-api/bpmn-model-api/

This is not an urgent request, but rather something we do see occasionally.

@akeller will review end of Q1 and pull in @menski for additional feedback.

**Comment by menski** [comment]
Could make sense to add also DMN model API

**Comment by menski** [comment]
Please note that DMN API has no builder API, which is challenging to use

**Comment by megglos** [comment]
@akeller is this still valid from your perspective? did we encounter users wanting to make use of the bpmn model artifact?
