### ISSUE TITLE
Document new Roles and Permissions in Camunda Cloud

### ISSUE THREAD

**Issue by urbanisierung** [camunda/camunda-platform-docs#451]
relates https://github.com/camunda-cloud/console/issues/2581

Spec: https://docs.google.com/document/d/1FZYFn9fK2sn6ksjh7drSNad1vyMEIwK6p4KlG353yfM/edit#heading=h.kjgwc8d48e3a

/cc @nazlikaya @felix-mueller

**Comment by akeller** [comment]
Is there will work to be done here?

**Comment by akeller** [comment]
I believe this work is done and available here - https://docs.camunda.io/docs/next/components/console/manage-organization/manage-users/#roles-and-permissions

If not, please reopen and prioritize.
