### ISSUE TITLE
DOCS: Create documentation for API

### ISSUE THREAD

**Issue by KatePopkova** [camunda/camunda-platform-docs#503]
Create documentation that describes how developers can use Zeebe in projects.

For example, for now it is some kind of problem to use Zeebe because there are no any description for classes, its fields and methods. It is not understandable what to use and how (I mean in code) for any task in the project that includes Zeebe therefore every time developers have to do some research of Zeebe source codes before using some Zeebe feature in the project that can take much time. When I say "documentation", I mean documentation for using Zeebe programmatically. Many frameworks and libraries have it, for example Spring Boot has documentation that describes every class: https://docs.spring.io/spring-boot/docs/2.3.0.M4/api//org/springframework/boot/configurationprocessor/json/JSONObject.html

**Comment by akeller** [comment]
Is this for enhancements to the [Zeebe API (gRPC)](https://docs.camunda.io/docs/next/apis-clients/grpc/)?

**Comment by megglos** [comment]
Hey @KatePopkova,
thanks for reaching out on this.

I'd like to understand your request better, when you refer to using Zeebe programmatically do you mean the zeebe clients (e.g. the java client which has some documentation [here](https://docs.camunda.io/docs/8.0/apis-tools/java-client/))?

As aside from the clients, we consider every other java component not to be public api and thus don't focus on documenting that beyond the javadoc that is anyway available through the maven artifacts.

**Comment by akeller** [comment]
Since there has been no responses and this issue is quite old, I will close it.
