### ISSUE TITLE
Upgrading Minor Versions Doesn't require patchs

### ISSUE THREAD

**Issue by NPDeehan** [camunda/camunda-platform-docs#571]
I found that if you wanted to upgrade your zeebe cluster from lets say 1.2.0 to 1.3.0 you don't actually need to follow the upgrade path of 1.2.1 -> 1.2.2 -> ..... -> 1.3.0 

You can run a single upgrade when moving from one minor version to another. 
The docs on the upgrading don't seem to mention this is, it would be good to have this explicitly stated.

**Comment by akeller** [comment]
@menski can you verify? Should we add this to the introduction page? https://docs.camunda.io/docs/guides/update-guide/introduction/

Additionally, these update guides serve both SaaS and CCSM users, right? I will cross-link from CCSM section if that's the case.

**Comment by akeller** [comment]
Let's get this closed out 😎
