### ISSUE TITLE
Document Zeebe broker admin endpoint

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda-platform-docs#59]
**Description**

We removed the admin endpoint documentation from the upgrade guide, primarily to avoid confusing as we're working the way Zeebe can be upgraded. However, it's still useful to have this documented, and we should documented it separately (which can then be linked back in the upgrade guide).

Ideally, please document each endpoint, expected request format, expected response format, etc. Something similar (but not necessarily as thorough) as https://docs.github.com/en/free-pro-team@latest/rest/reference/actions.

**Comment by akeller** [comment]
@menski can you please assign someone to work on this?

**Comment by akeller** [comment]
Is this relevant anymore?

**Comment by npepinpe** [comment]
This is relevant for self managed customers, as the admin endpoint provides more observability. It's pretty advanced though, so I expect most users will not need to deal with it for now. We could close it until we want to approach it again.

**Comment by megglos** [comment]
Deepthi: We should move admin endpoints to the Gateway instead, and document it there.

Pauseprocessing, Streamprocessing and TakeSnapshot are left to move.
@deepthidevaki will create a ticket for that.

Closing this as it's not worth doing under that perspective.
