### ISSUE TITLE
Rename branch `master` to `main`

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#634]
This is long overdue, but something I'd like to prioritize. 

https://github.com/github/renaming

---

### Steps

- [x] Communicate to #ask-documentation that this change will be made
- [x] Rename master to main in this repo
- [x] Update the "edit this page" URL in docusaurus.config.js (#918)
- [x] Update the build configuration files (#918)
- [x] Deploy to production
- [x] Communicate to #ask-documentation that this change has been made
- [x] Wait five days to see if anyone complains about things being broken, then close this issue.

**Comment by akeller** [comment]
@pepopowitz have you done this before? I have, but never with a project that had GitHub Actions and other scripts running on it (some of our screenshots are automated). 

We are planning to move this repo into github.com/camunda very soon so I don't suggest we do this branch renaming immediately, but can you think of any issues we may have with this other than the ones I mentioned above with GitHub Actions and other scripts? 

I won't assign anyone quite yet until we figure out when we will do this and what things we may run into along the way.

**Comment by pepopowitz** [comment]
I've done this for a few projects, and I agree the worst part is definitely any other processes that rely on the branch name. 

It looks like the github actions should take only a couple lines of changes: [here](https://github.com/camunda-cloud/camunda-cloud-documentation/blob/f2c23eb07fa997910565e0d21be6c3fa798f8be2/.github/workflows/publish-stage.yaml#L6) and [here](https://github.com/camunda-cloud/camunda-cloud-documentation/blob/f2c23eb07fa997910565e0d21be6c3fa798f8be2/.github/workflows/build-docs.yaml#L7). We'll also want to update [the docusaurus config](https://github.com/camunda-cloud/camunda-cloud-documentation/blob/f2c23eb07fa997910565e0d21be6c3fa798f8be2/docusaurus.config.js#L217). 

I'm not sure what the other scripts are though. Are they within this project, or somewhere else? Is it feasible to make the name change, and then see what breaks?

**Comment by akeller** [comment]
@christinaausley you are our resident expert in the screenshot automation scripts 😉 . Do you know if these are tied to the name of the branch used? Can you point @pepopowitz in the direction of those scripts? I know the Modeler team has one and I believe it's in an [internal repo](https://github.com/camunda/camunda-docs-modeler-screenshots). Let us know if you need access to have a look.

**Comment by christinaausley** [comment]
Take a look inside the [`lib`](https://github.com/camunda/camunda-docs-modeler-screenshots/tree/main/lib) folder for a closer look at the script for screenshot automation. As far as I can tell, all that needs to remain the same is the file/image name and the repo, as shown below in a screenshot from this repo's `package.json`. Let me know if you have additional questions about this.
<img width="1340" alt="Screen Shot 2022-04-19 at 5 36 54 PM" src="https://user-images.githubusercontent.com/84338309/164118385-e69e40c9-1030-42b4-82e9-82fdc27738ef.png">

**Comment by akeller** [comment]
@christinaausley can you go ahead and create an issue against that repo to update the line there?

**Comment by akeller** [comment]
> Take a look inside the [`lib`](https://github.com/camunda/camunda-docs-modeler-screenshots/tree/main/lib) folder for a closer look at the script for screenshot automation. As far as I can tell, all that needs to remain the same is the file/image name and the repo, as shown below in a screenshot from this repo's `package.json`. Let me know if you have additional questions about this. <img alt="Screen Shot 2022-04-19 at 5 36 54 PM" width="1340" src="https://user-images.githubusercontent.com/84338309/164118385-e69e40c9-1030-42b4-82e9-82fdc27738ef.png">

Sounds like it won't have any impact for this issue but will be impacted by #822.

**Comment by pepopowitz** [comment]
Capturing a list of things I intend to do when I rename this branch (and I'll copy these into the issue body, too): 

- Communicate to #ask-documentation that this change will be made
- Rename master to main in this repo
- Update the "edit this page" URL in docusaurus.config.js 
- Update the build configuration files
- Deploy to production
- Communicate to #ask-documentation that this change has been made
- Wait five days to see if anyone complains about things being broken, then close this issue.
