### ISSUE TITLE
Clarifying reports in Optimize

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#692]
Separate from linking and likely another PR - I wasn't sure if a **Combined report** was a different kind of report. From the screenshots, it looks like there are 3 options - Process Report, Combined Process Report, and Decision Report. Is this a "Combined Report" or a "Combined Process Report" or does the name not really matter here and can be used interchangeably? (This is likely a product management question for Eric.) Does this mean Process Reports and Decision Reports are both described in the single report section of **Creating reports**?

_Originally posted by @akeller in https://github.com/camunda-cloud/camunda-cloud-documentation/pull/679#pullrequestreview-912097655_

**Comment by akeller** [comment]
@christinaausley do you think this issue is still relevant after the restructure of the Optimize content?

**Comment by christinaausley** [comment]
There weren't any changes to this in the Optimize restructure other than confirming that it is Camunda Platform 7 only, but I've followed up with @HanselIdes for thoughts on how we can clarify in the docs.

**Comment by HanselIdes** [comment]
@christinaausley / @akeller 
Combined Report and Combined Process Report are interchangeable.
The UI uses Combined Process Report, so I suggest consolidating around that terminology in the short term
<img width="393" alt="image" src="https://user-images.githubusercontent.com/17521551/179940891-992902b9-96d1-4538-bcb4-44a5421ab327.png">

Sometime in the future, Combined Reports will be deprecated and we'll use Process Reports with multiple data sources instead. However, there's a [bug](https://jira.camunda.com/browse/OPT-5574) that needs to be fixed before Combined Reports can uniquely solve for some user problems (specifically, comparing different slices of the same data)

**Comment by akeller** [comment]
@christinaausley can I assign this to you to use "Combined Process Report"? That will close out this issue.

**Comment by christinaausley** [comment]
@akeller Absolutely -- I'll adjust any references in a PR.
