### ISSUE TITLE
Go getting started guide is broken

### ISSUE THREAD

**Issue by pihme** [camunda/camunda-platform-docs#773]
The go getting started guide is broken.

If you follow it to the letter from scratch (without cloning the repo), it will produce a warning message hat `go.sum` entries are missing.

The easiest way we found to fix this was to run `go mod tidy` before running the go code.

So in the best case, this step just needs to be added to the guide.

There might be a more common way in the go community though.

**Comment by pihme** [comment]
Also still references old location `camunda-cloud` vs `camunda` in the source examples

**Comment by akeller** [comment]
Is this still an issue?

**Comment by megglos** [comment]
@akeller it looks outdated to me, e.g. it refers to the 8.0.0 version of the zeebe client 
https://docs.camunda.io/docs/apis-tools/go-client/go-get-started/

would that be something your team can take over and if needed requests help?

**Comment by akeller** [comment]
DevEx will take this.
