### ISSUE TITLE
Improve component overview page

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-platform-docs#783]
improve https://docs.camunda.io/docs/components/

especially "[Cloud Console](https://docs.camunda.io/docs/components/console/introduction/) - More information on working with Cloud Console."

- [ ]  Add short description of what each component does (can reuse meta description on components' overview page)
- [ ] Add Best Practices to list w/ short description

Scope: 8.2, `next`

**Comment by akeller** [comment]
@felix-mueller can I assign this to you and have you work with @christinaausley on the content? Is this something you are hoping to finish before `release-1.4.0`?

Small spoiler - I do want to customize this page with component logos and a clickable architecture diagram so it's a little more engaging 😄

**Comment by akeller** [comment]
@christinaausley this looks like a quick win. Can I get this on your radar? It's not urgent, so please prioritize it against your work.

**Comment by christinaausley** [comment]
I'll plan to tackle this later this week or early next week @akeller 👍 Happy to assist. Can also discuss in our 1:1 tomorrow.
