### ISSUE TITLE
Update Connectors in Best Practices

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-platform-docs#784]
we found [this page](https://docs.camunda.io/docs/components/best-practices/development/connecting-the-workflow-engine-with-your-world/) of yours where you described how to connect the workflow engine with the world. This pages contains remarks about Connectors and that there are no in SaaS etc. which will be outdated next week. Would you be able to support us by updating this page incorporating the availability of cloud connectors? You can find our [work in progress here of the connectors docs](https://github.com/camunda-cloud/camunda-cloud-documentation/pull/725)?

**Comment by akeller** [comment]
@berndruecker @menski is this done?

**Comment by menski** [comment]
No

**Comment by berndruecker** [comment]
Nope - still on my list. Fingers crossed for next week

**Comment by akeller** [comment]
@berndruecker is this done?

**Comment by berndruecker** [comment]
Of course not :-| 
Popped up my trello card for it and then hope to overwork the whole connector parts with the latest connector developments (probably around new year)

**Comment by akeller** [comment]
Your weeks are much longer than mine 😝

**Comment by akeller** [comment]
Closing this issue as it's a bit stale. Please see this [doc](https://docs.google.com/document/d/1VB_cDTaNfdyT6xyHj_YlYJfW76Rt76LYsls7AsIqpZQ/edit#heading=h.cv58mxb2xmxo) as part of https://github.com/camunda/product-hub/issues/1005.
