### ISSUE TITLE
Enrich GraphQL Documentation for the Tasklist API

### ISSUE THREAD

**Issue by Hafflgav** [camunda/camunda-platform-docs#794]
The current GraphQL API documentation is generated and provides a good point as reference. 
I am missing a section containing some general information. Containing for instance: 

- What is GraphQL 
- How Can I work with GraphQL? 
- Run a query in `curl` 
- Short Example? - similar to our REST docu but not for every query 
- Further reading about queries, mutations, ... 

I think it is worth checking out the GitLab docs. I really like how they structures that section. 
https://docs.gitlab.com/ee/api/graphql/ 

Let me know what you think! 
Tagging @akeller & @berndruecker for now ;)

**Comment by akeller** [comment]
@Hafflgav GraphQL and I have a long history of trying to figure out how much documentation I want to support and how much I want to punt over to other resources for beginner content. I do think this makes an excellent blog series. 

I'd like to take this topic into my strategy session next week to come up with a plan for how to tackle this.

**Comment by Hafflgav** [comment]
Awesome! Thanks for the update. I am actually currently writing such a blogpost at the moment. If you decide to update that content I am happy to assist you. I think we could repurpose some sections of the blogpost. ;)

**Comment by akeller** [comment]
This is going to be a long-winded explanation so I can try to answer current and future questions about GraphQL content in docs at Camunda but the short answer is **I would not include general or beginner information on GraphQL in the documentation at this time**.

While I like the GitLab content you referenced, they are "all in" on GraphQL, whereas Camunda is not (yet?). We support REST, gPRC, and GraphQL, with the bulk of our users having some experience in REST in either C7 or C8. This does leave a fair amount of room for educational content for all these interfaces, not just GraphQL. Everything we pull into the official docs has a maintenance cost. 

I would recommend updating the [overview](https://docs.camunda.io/docs/apis-clients/tasklist-api/overview/) and the [tutorial](https://docs.camunda.io/docs/apis-clients/tasklist-api/tutorial/) to make sure it accommodates users who are new to Camunda Tasklist and GraphQL looking to answer the question - how would developers be successful learning the minimum of each? Then throughout the pages or at the bottom, we can include additional resources that teach more in-depth GraphQL topics. This supports the lazy path (give me exactly what I need to be successful) as well as the guided educational path (give me curated links to learn more about this topic so I don't have to search around myself). 

If you are interested in personally maintaining beginner GraphQL content, I would recommend curating a repo on the Camunda Community Hub. We could also link to that from the documentation. This would also give the community an easier way to include their favorite GraphQL resources and maybe we could learn a thing or two!

If we do decide to make more of an investment in GraphQL, I'd like to revisit pulling in beginner GraphQL content into documentation and even adjust the overall docs vision to include more beginner content for APIs. 

Specifically for your blog, I've done [this before](https://dev.to/missamarakay/graphql-for-consumers-who-don-t-want-to-use-libraries-3nbf). You'll see references from my previous company's GraphQL API where we used GraphiQL, Postman, cURL, and investigated other tools like [Insomnia](https://insomnia.rest/). This may be a good opportunity to work with @pepopowitz and see if he has any favorite tools and resources for working with GraphQL.

**Comment by pepopowitz** [comment]
I have a good amount of experience with GraphQL from my previous job. I don't know that I have specific learning resources to point you at @Hafflgav, but let me know if you have specific things you'd be looking for, and I'm happy to look.

In general I agree with @akeller regarding pointing learners at other resources for GraphQL, instead of teaching it to them in our own docs. The one thing I'd add is that it might be useful to tell them the entry requirements, so they know if they need to go somewhere else to learn GraphQL before they explore our docs. This might take the form of a code sample that basically says "if you can explain this in full, you will understand everything in our docs. If not, you should go to ____ to learn a, b, c, and d."

**Comment by Hafflgav** [comment]
We decided to not include a fundamental guide to our documentation. If you stumble across this issue you can find some more information about how to get started with graphQL in this blogpost: https://camunda.com/blog/2022/05/getting-started-with-camunda-platform-8s-graphql-api/
