### ISSUE TITLE
Move repo to github.com/camunda & update README

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#822]

**Comment by akeller** [comment]
@christinaausley can you create an issue against the repo you mentioned in your comment on #634 to update the line when this repo is moved?

**Comment by christinaausley** [comment]
Note that an issue has been created in the Modeler screenshot repo and can be tracked [here](https://github.com/camunda/camunda-docs-modeler-screenshots/issues/33).

**Comment by akeller** [comment]
This is complete.
