### ISSUE TITLE
Mention SaaS in docs

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-platform-docs#828]
I did not find any good site/resource I could easily link if I want to point people to SaaS.

We should have such a site

See e.g. discussion in #814: 
![grafik](https://user-images.githubusercontent.com/1217596/164386237-44836ae5-87d5-41e3-8959-6f17392b8007.png)

**Comment by akeller** [comment]
@berndruecker are you looking for a definition of SaaS? The idea is all items on docs.camunda.io are SaaS-first unless otherwise mentioned as noted here - https://docs.camunda.io/meta/#structure.

**Comment by akeller** [comment]
@berndruecker is this still something you'd like us to work on?

**Comment by akeller** [comment]
Closing this as stale. I believe it's complete, but not by a specific issue or PR.
