### ISSUE TITLE
Rewrite Optimize self-manage documentation

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-docs#845]
With https://github.com/camunda/camunda-platform-helm/issues/126 we will support Optimize in the Helm charts. We need to adjust the helm chart docs with respect to that. Furthermore, we need to adjust the optimize section itself since it mentions it is for camunda 7 only. We probably need to adjust several sections.

**Comment by akeller** [comment]
@megglos is this still relevant? Should we handoff to @RomanJRW and team? Or is it already documented here - https://docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/deploy/#components-installed-by-the-helm-charts?

**Comment by megglos** [comment]
Hey, yes let's definitely hand this over, @RomanJRW can you check whether that is still valid?

**Comment by RomanJRW** [comment]
We no longer document Optimize as C7-only and it is included in the helm charts docs, so I will close this as I consider it done. Thanks for flagging
