### ISSUE TITLE
As a Zeebe user, I want to see a migration guide about removing monitoring properties in Zeebe Gateway

### ISSUE THREAD

**Issue by aivinog1** [camunda/camunda-platform-docs#861]
I think that [this commit](https://github.com/camunda/zeebe/commit/d275ca8f12795861d0ec5f1391a489aba0a70417) should be mentioned [there](https://github.com/camunda-cloud/camunda-cloud-documentation/blob/master/docs/guides/update-guide/120-to-130.md) with recommendations about migration.

**Comment by npepinpe** [comment]
Just to clarify, you mean the removal of the configuration properties in the gateway config (e.g. `zeebe.gateway.monitoring`), and not some other functionality (e.g. missing metric or endpoint)?

**Comment by aivinog1** [comment]
Hey @npepinpe! Yes, I mean the removal monitoring configuration properties :)
