### ISSUE TITLE
Human task get started guide is broken in regards to forms

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-platform-docs#862]
Looking at https://docs.camunda.io/docs/guides/getting-started-orchestrate-human-tasks/

I miss how to add the form to the process model - this is not really mentioned in the flow:

![grafik](https://user-images.githubusercontent.com/1217596/165519389-87b51028-3913-4b77-80d7-16b29d829612.png)

The description says how to define the form, but not how to add it to the model / deploy it. The link further down leads you to https://docs.camunda.io/docs/guides/utilizing-forms/ which is not really C8-targeted.

You have to find your way yourself to navigate to https://docs.camunda.io/docs/components/modeler/bpmn/user-tasks/#user-task-forms to understand, that you have to manually copy the JSON of the form into the User Task of the BPMN model. 

I think we should 

- add that step to the guide to make it clear
- remove the link to the C7 content
- Add a link to https://docs.camunda.io/docs/components/modeler/bpmn/user-tasks/#user-task-forms instead

**Comment by berndruecker** [comment]
@christinaausley is this something that you could look after? Is the description clear enough?

**Comment by christinaausley** [comment]
@berndruecker Great feedback. I'll launch a PR this week based on this issue to adjust.
