### ISSUE TITLE
SendGrid Connector Using process variables

### ISSUE THREAD

**Issue by davidgs** [camunda/camunda-platform-docs#882]
The Sendgrid Connector example is super useful right up to this point:

```
= {
  name: "Jane",
  location: "Berlin",
  weather: "Clear",
  actual-temp: 30,
  feel-temp: 3
}
```

This assumes that you *always* want to sent the email to the same person, with the same data. In the example, we are sending a weather report to a user. However, this example would send the exact same weather report (actual temp 30, feel-temp 3, weather clear) all the time. 

A more useful example would be to show how to substitute process variables into that FEEL expression so that the example shows how to send an actual weather report based on data other than static values.

**Comment by mary-grace** [comment]
@davidgs Sounds like you have an idea of a solution for this already! Any chance you could submit a quick PR for review? That way it would be a fairly quick win for the team to review & push it live.

**Comment by davidgs** [comment]
@mary-grace Done. PR #885
