### ISSUE TITLE
Clients: Console OpenAPI spec hard to find

### ISSUE THREAD

**Issue by Sijoma** [camunda/camunda-platform-docs#930]
The page https://docs.camunda.io/docs/apis-clients/console-api-reference/ contains information on the REST api of Console. It gives some information at the beginning. But in my perspective the most important link to the actual OpenAPI specification is a bit hard to find. The link is mentioned last in the page. Additionally, it also does not mention OpenAPI / Swagger which is quite known and probably a term users search for. 

This specification is the closest thing to figure out what a user can actually do with the API.

**Comment by akeller** [comment]
@christinaausley This feels like mostly a presentation issue. Can you look at making this link more obvious and near the top of the page?
