### ISSUE TITLE
Split Optimize common problems into C7 only, C8 only, or all

### ISSUE THREAD

**Issue by HanselIdes** [camunda/camunda-platform-docs#933]
The [Optimize Common Problems page](https://docs.camunda.io/docs/self-managed/optimize-deployment/configuration/common-problems/) has a C7 Only tag, but I'm sure at least one topic applies to C8SM (e.g. update issues)

**Comment by RomanJRW** [comment]
OPT ticket: https://jira.camunda.com/browse/OPT-6948
