### ISSUE TITLE
Update compatibility pills for some general API endpoints 

### ISSUE THREAD

**Issue by HanselIdes** [camunda/camunda-platform-docs#936]
([Delete dashboards | Camunda Platform 8](https://docs.camunda.io/docs/self-managed/optimize-deployment/rest-api/dashboard/delete-dashboard/)) ([Delete reports | Camunda Platform 8](https://docs.camunda.io/docs/self-managed/optimize-deployment/rest-api/report/delete-report/)) ([Export report result data | Camunda Platform 8](https://docs.camunda.io/docs/self-managed/optimize-deployment/rest-api/report/get-data-export/))

**Comment by RomanJRW** [comment]
Optimize ticket: https://jira.camunda.com/browse/OPT-6944
