### ISSUE TITLE
Document support of enterprise IDP in SaaS via auth0

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-platform-docs#950]
Document that we support enterprise IDP in SaaS via auth0:
https://auth0.com/docs/authenticate/identity-providers/enterprise-identity-providers

**Comment by akeller** [comment]
@ultraschuppi is this possible today? SAML and Azure AD are in the [docs](https://docs.camunda.io/docs/components/console/manage-organization/external-sso/) but no Auth0.

**Comment by ultraschuppi** [comment]
@felix-mueller we should not advertise stuff that we didn't build first. 

right now, only SAML and azureAD are supported. any of the other listed are _most probably_ possible, but without properly adding it into accounts we will not be able to follow the same procedures that we already have established.

**Comment by felix-mueller** [comment]
@ultraschuppi I agree, the ticket is outdated. a year ago when created this ticket I thought we could simply just support all, but learned on the way. let's close it

**Comment by ultraschuppi** [comment]
> @ultraschuppi I agree, the ticket is outdated. a year ago when created this ticket I thought we could simply just support all, but learned on the way. let's close it

@felix-mueller  oh haha, wasn't aware we are doing ticket-archeology here ;)
