### ISSUE TITLE
As a reader of the documentation, I expect to see changes in deprecation of the `contactPoint` property

### ISSUE THREAD

**Issue by aivinog1** [camunda/camunda-platform-docs#958]
After https://github.com/camunda/zeebe/pull/9508 will be merged we should update the docs in the following topics:
1. Describe that the `contactPoint` property is deprecated
2. Describe that we have a replacement for this:
   1. Describe the new `initialContactPoints` property 
   2. Update migration guides

**Comment by aivinog1** [comment]
Hello @akeller @Zelldon! 

If @Zelldon is too busy or unavailable, I can propose a PR to this as well :)

**Comment by Zelldon** [comment]
Hey @aivinog1 that would be great!

**Comment by akeller** [comment]
Looks like this was merged. Are we good to close this issue?
