### ISSUE TITLE
I can read about job backoff

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-platform-docs#964]
With Zeebe `8.1`, we added a new feature to specify a backoff when failing a job (https://github.com/camunda/zeebe/issues/164). 

We need to add documentation for it. This included:

- [ ] update the gRPC API docs: https://docs.camunda.io/docs/apis-clients/grpc/#failjob-rpc
- [ ] extend the job worker docs: https://docs.camunda.io/docs/components/concepts/job-workers/#completing-or-failing-jobs

**Comment by pierre-yves-monnet** [comment]
Hello,
Comparing this document with C7 feature, I have the feeling this  is not possible for the service task (the worker) to specify a delay before the retry. 
_" if the retries argument is positive, the job is immediately activatable again, and a worker could try again to process it."_

in C7, if I'm correct, it is possible for a worker to specify a delay before propose again the job to a worker. A I'm correct?

**Comment by saig0** [comment]
The new feature makes it possible for a job worker to define a backoff when marking a job as failed. As a result, the job will not be retried immediately but after the given duration. Similar to the feature in Camunda Platform 7.
